### ISSUE TITLE
Project with existing source dialog opens with wrong project path

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#105]
- Create a new project somewhere in the system, i.e. `/User/Desktop`
- Have some source in some other folder location to create a new project with, i.e. `/User/Documents/MyNewProject`
- Click on 'Open Apache Flex/JS Project' link in splash screen (Moonshine)
- This will open a file browser dialog, navigate to `/User/Documents/MyNewProject` and select
- Moonshine alerts that no project exists in that path and if user wants to create a new project in the given directory - select Yes
- New project creation dialog opens but 'Project directory' shown wrong location - `/User/Desktop` instead of `/User/Documents/MyNewProject`
- Continue creating a project by locating source folder and source file to the project creation dialog caused project created at `/User/Desktop` with incorrect folder generation

**Comment by rat-moonshine** [comment]
This problem seems introduced after the fix of #93 , so it's possible that 1.7.0 port with this problem as well. Now fixed.

**Comment by JoelProminic** [comment]
I confirmed this is broken in the 1.7.0 App Store release.

Do you guys feel that this bug is significant enough to require an early 1.7.1 release?

The users can work around this by creating a new project and using the "Project with existing source" option.

Here is a more detailed test procedure:
1. Delete the .as3proj file from an old AIR project
2. Open Moonshine
3. From the Home screen, click "Open Apache Flex/JS Project"
4. Moonshine reports:  "This directory is missing the Moonshine project configuration files.  Do you want to generate a new plroject by locating existing source."
5. Click Yes
6. The New Project window appears.  BUG.  The "Project directory" is set to the parent directory of the selected project
7. The Project Name is "ExportedProject".  Change it to match your project name.
8. Click Create - get an error indicating that the project already exists
9. Change the name 
10. Click Create - get errors for a missing src and base application file
11. Populate the src directory and default application file.  NOTE: the filechooser resets to the Desktop directory each time
12. Click Create
13. BUG:  the project files are created in the parent directory, rather than in the target project directory.
14. Create a new project
15. BUG:  The default Project directory is the parent directory of the previously selected parent directory.

I confirmed that this is fixed with the latest 1.8.0 build.

**Comment by piotrzarzycki21** [comment]
@JoelProminic it look to me enough serious to have the 1.7.1 release. We will make appropriate preparations and start the process.
