### ISSUE TITLE
Code Completion should show suggestions which contains words in any position

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#121]
Code completion should show items even if typed word is in the middle of items name.

Typing "List" should show in code completion all items which contains it:

List
CodeList
MyListOfItems

Currently in above case we will see on the CC only:

List

**Comment by JoelProminic** [comment]
I confirmed the updated behavior.  The lookup seems fast as well.

One potential improvement would be to highlight the matched characters so that it is immediately clear that a match was found because of the new search logic.  This may be overkill, though:
![image](https://user-images.githubusercontent.com/24532731/34696492-a9034dca-f494-11e7-9603-3ec6ea488bf4.png)
