### ISSUE TITLE
[UI Builder] Misc. enhancement requests

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#138]
1. Add ability to resize right-hand panel (property editor)
2. Pressing tab inside input fields in right-hand panel focus cursor back to the stage/component. Expected - move the cursor to next text input field (if available)
3. In case of the dropdown component, it would be great if the selected item in property editor list can be selected label in the dropdown UI
![image](https://user-images.githubusercontent.com/24370870/34824018-befe93fe-f6f2-11e7-85c6-4ba0d1fed526.png)

**Comment by piotrzarzycki21** [comment]
1. Ability to resize property editor has been added.

**Comment by piotrzarzycki21** [comment]
2. It looks like jumping by tabs through those inputs is something harder than I thought. It is because Visual Editor in Moonshine is a separate component from external SWC. When I'm trying to use tab I'm loosing focus on the property editor and tab won't work. I will probably try to prevent that using `FocusEvent.KEY_FOCUS_CHANGE`. Once I prevent loosing focus I may be able programmatically switch to the next text input.

**Comment by piotrzarzycki21** [comment]
2. I have fixed Tabs for property editor, but only for the area with basic property. I think for now it will be satisfactory.

**Comment by piotrzarzycki21** [comment]
3. I did add that option.
Take a look into my changes. If you have something more let me know here or close that issue.

**Comment by rat-moonshine** [comment]
1. Looks good, this should be adequate for the time being.
2. Works nice!
3. Looks good, too.

I'm closing the issue for now, we can revisit this later again if we want some more of this small improvements.

**Comment by atinprominic** [comment]
It looks good.
