### ISSUE TITLE
Prevent from creating project in existing project directory

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#140]
I able to create a new project inside an existing project in following way:

- A new project created at `/User/NewProjectA`
- Open project creation dialog to create a new project
- In "Project Directory" path you choose `/User/NewProjectA`
- You choose "Project with existing source"
- Map an application file in the followed by options

Moonshine successfully creates the newer project without giving any permission error. When the new project created `/User/NewProjectA` holds two different .as3proj file.

Project creation in another project root must be restricted.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine could you change title of that issue ? Whenever I'm seeing it I don't know instantly what is all about. Maybe something: "Prevent from creating project in existing project directory" ?

**Comment by piotrzarzycki21** [comment]
I don't have any comments to that. Changes seems to be helpful.

**Comment by atinprominic** [comment]
The feature of existing source code is still confusing. It allows to create the project in non empty directory and it might create issues. Lets take a scenario:

1. There is the folder named C:\Projects. It has many subfolders in it each for a project. E.g. : C:\Projects\Prj1, C:\Projects\Prj3, C:\Projects\Prj4 etc
2. Along with multiple folders in C:\Projects, there is an existing folder named C:\Project\ExistingSource
3. The developer wants to create a new Moonshine project.
4. Out of general practice as he follow while creating regular Moonshine projects, he select the directory - C:\Projects and specifies the project name - "MyNewProject"
5. Then he opts for using existing source and specifies the existing source directory to be C:\Projects\ExistingSource
6. Now he creates the project
7. The project is created inside the directory C:\Projects as the project directory. Here the point to be noted is that the new project directory is not created and the project is created inside the C:\Projects directly. Its created as its an existing source project.
8. The developer has not noted about the different behaviour of project directory treatment in case of existing source. As the developer mostly creates the new projects without existing source, he has an impression that a new project directory will be created with the project name specified.
9. Now the developer has done with the project and he needs to delete the project due to any reason and he is fine if everything inside C:\Projects\ExistingSource is deleted.
10. After deletion, he came to know that everything inside C:\Projects is deleted.
11. Its a very horrible situation for the developer and he will think 10 times again in the future before using Moonshine IDE.

My Suggestion:
1. We should ask the path to the project directory again from the user once he has specified the existing source.
2. We should show the full absolute path to the project directory being deleted when he deletes the project from within moonshine.

Thanks
Atin

**Comment by piotrzarzycki21** [comment]
If we are in the process of creation project from source - I think we have all path specified on our view. Maybe we could display more information.

I'm not a big fun of displaying a full path on users prompt to the project which we are trying to delete. On window paths something are really long, and they won't be readable in such prompt.

Maybe we should go with different path. Do not allow users delete project. If user choose "Delete" project, we should delete only Moonshine project files, not sources. It resolves problem above. 

Thoughts ?

**Comment by rat-moonshine** [comment]
> Maybe we should go with different path. Do not allow users delete project. If user choose "Delete" project, we should delete only Moonshine project files, not sources. It resolves problem above.

Any IDE gives functionality to delete a project folder from its UI. So, I don't think it'd be good to remove delete project feature from the Moonshine. 

I'm not clear about what you meant by 'delete only Moonshine project files, not source' @piotrzarzycki21 . Does that mean that not to delete the folder but its files? 

Even if that so, we shall again returning to the bad project creation to ~/Documents folder. Because if the project get created at ~/Documents, all of its files/folders suppose to get the project's source files/folders. So deletion of files/folders inside a project anyway give same impact. 

For showing full path when project deletion - we may can show that, in alert. Although, the full path to the project is also shows when mouse-over the project root in sidebar.

**Comment by JoelProminic** [comment]
I created a mockup to help brainstorm how we might change the Import Project form to make it more clear:
![image](https://user-images.githubusercontent.com/24532731/35177502-89634934-fd45-11e7-9f55-aa54f9fbf82b.png)

I found that the layout isn't that much different, though.

I have attached my mockup (from Balsamiq Mockups) if someone else wants to tweak it:

**Comment by rat-moonshine** [comment]
I get the idea now, @piotrzarzycki21 . I think we can do that at least. Removing source and relevant project files.

What is your suggestion on this @JoelProminic ?

**Comment by piotrzarzycki21** [comment]
>  Removing source and relevant project files. 
I hope you did mean by "sources" only Moonshine file, not project source folders like "src" or library folder "lib" etc. :)

**Comment by rat-moonshine** [comment]
Why not project's "src"? When all the source files suppose to reside inside that folder only, and surely Moonshine should not go individually delete each file, but the source folder file, i.e. 'src'. 

When the project calls for a deletion, then all of the project's resources are suppose to get deleted, isn't it? Including its 'libs', 'src' etc. files/folders which are relative to the main project folder.

**Comment by piotrzarzycki21** [comment]
It looks like you didn't understand my idea. :) My idea is - If user decide delete project - IDE should protect the sources and delete only project files, created by that IDE. 
After deletion basically you will not able to open project again, unless you "Create project from sources" again.

**Comment by piotrzarzycki21** [comment]
What's your thoughts on that idea guys ?

**Comment by rat-moonshine** [comment]
Personally, I'm not very preferred to keep the source files/folders when a project is being deleted by the user with his/her full concern (even, if that how things been handled in another IDE). However, deleting the files/folders from the project directory of which Moonshine can keep track of - I'm interested to that direction. But, in my preference, the source folder should be deleted along with the project's other corresponding files.

**Comment by piotrzarzycki21** [comment]
Ok let's move forward even with removing all files. In that case we need to have clean message to the users what will happen.

**Comment by rat-moonshine** [comment]
We should also take opinions from @JoelProminic on this before we actually make those changes to the Moonshine, I guess.

**Comment by piotrzarzycki21** [comment]
Yep definitely we should wait for Joel.

**Comment by JoelProminic** [comment]
I don't see a major use case for Piotr's suggestion of deleting only the project configuration files.   Eclipse has a similar option to this, but this is needed to remove a project from the workspace.  In Moonshine, we would just close the project.  In any case, I don't think this is what the user would expect from a Delete operation.

Santanu's suggestion of removing the project files and src directory would leave the rest of the directory structure (parent directory, bin, bin-debug, custom directories) untouched.   I feel this also does not match the expectations for a Delete action.

So, if we want to continue deleting all files in the directory, we would want to make it clear which files would be deleted.

My thought for this would be to show a tree of the files to be deleted in the confirmation dialog.

![image](https://user-images.githubusercontent.com/24532731/35349746-6d0eda04-0101-11e8-8cc4-0a85827a7450.png)

Some notes
- The tree would be collapsed by default so that the default case is easy to read
- Show the actual directory names (to catch the Documents case Atin described)
- The user can't select which files they want to delete or keep (though that could be a future improvement if there was interest)
- This interface could be used for other directory or file deletes as well.  
- This doesn't display the absolute path, but the user could recognize other directories by the directory name or contents.

Does this look good?  This could be resource intensive for a directory like Documents, but we would be having trouble in the sidebar already in this case.

**Comment by rat-moonshine** [comment]
As a small correction (I maybe was not properly expressed my thoughts), my vote was to delete all the files/folders that Moonshine can track against a project, including its 'bin', 'bin-debug', 'build' etc. folders. Source file folder should also suppose to be deleted in this process as well, including the project's configuration files.

I think it's transparent enough to have a window as described above by @JoelProminic , where we can show the files/folders which Moonshine keeps track against a project. 

@piotrzarzycki21 do you think the above make sense? If so, I shall want to move this change requirement to a separate issue and close this one, as this particular issue (#140) has been resolved.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I'm ok with that, although I'm not a big fun of deleting sources. :) This window looks good.

**Comment by rat-moonshine** [comment]
I have created a new issue #148 to keep track of the project deletion changes. Since the original requirement of this issue has met, I'm closing this issue for now.

**Comment by atinprominic** [comment]
While testing I found the issue. Its allowing me to create the project inside the project. If giving warning only if I chose the project name to be the default. Please test it again at your end.

**Comment by rat-moonshine** [comment]
@atinprominic did you meant you able to create a project to an existing project root folder? Example:
- You have an existing project folder /Documents/MyExistingProject
- You can able to create a new project to /Documents/MyExistingProject?

The recent fixes suppose not to create a new project in an existing project root folder. This is doable through checking existence of certain project configuration files. Please, confirm if you can still able to do that. 

However, you can able to create a new project inside /Documents/MyExistingProject/ABC/EFG or /Documents/MyExistingProject/ABC/EFG/IJK/LMN/ORP folder. This is doable, because its not logical and out of the box to do an uncertain amount of back folder check for an possibility of project configuration file existence.

**Comment by atinprominic** [comment]
@rat-moonshine Yes, I am able to create. Please refer to the attached screenshot for reference.
![screen shot 2018-01-31 at 3 13 59 pm](https://user-images.githubusercontent.com/34882311/35615887-7e243440-0699-11e8-8135-fe5a55daa8cc.png)
