### ISSUE TITLE
Add brackets to function/method after choose from code completion

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#146]
The enhancement has been brought in the discussion in #136 
As part of that enhancement cursor should be placed inside brackets.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just added that, take a look and let me know whether it is ok.

**Comment by JoelProminic** [comment]
To clarify, did this issue change anything except  completing the parenthesis for methods added in attributes?  "Brackets" makes me think of curly brackets, but that doesn't make sense when completing the method name.

I tried this again with the creationComplete case from #136, and it added the parenthesis and put the cursor between the parentheses so that I could add parameters (if desired).
