### ISSUE TITLE
Find Resources popup should remember previously selected filtering

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#168]

**Comment by piotrzarzycki21** [comment]
Filtering is remembered. I have extracted additionally logic to separate FindResourcesPlugin.

**Comment by JoelProminic** [comment]
The settings are preserved while Moonshine is running.  When I restarted Moonshine on macOS, the settings reset - was this intentional?

I'm a little concerned that the saved settings could be a problem if the user forgot that they had added a filter.  This could cause a class to be unexpectedly missing from the prompt.   If the user is using this functionality all the time, then this is probably not a problem.

How are you using this feature currently?  If you have a set filter that you almost always want to be using, then you will probably want to fix the first issue, and ignore my concern.

**Comment by piotrzarzycki21** [comment]
Filtering Settings for Find Resources are preserved only for current instance of Moonshine in that case. Same working Global search.
Answering to your question - yes it was intentional.
