### ISSUE TITLE
Option for selecting project in Global Search

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#170]
It could be some kind of DropDownList with currently opened projects.

**Comment by rat-moonshine** [comment]
If we introduce a dropdown (against projects), then following option (2nd) will not be relevant anymore:

![image](https://user-images.githubusercontent.com/24370870/35914762-71e1e4de-0c2a-11e8-894f-711978f3da9e.png)

**Comment by piotrzarzycki21** [comment]
Yep and it is even better, because It is really annoying me. When I have 4 projects open and hit Ctrl + H, I have to check whether I have proper one selected. Drop down will be much better. Btw what actually doing "Enclosing projects" ?

**Comment by rat-moonshine** [comment]
Enclosing Projects options basically works against the external source attached (`projects > Settings > Paths > Class Paths`). So if you consider to search on MoonshineDESKTOPevolved, it shall search through MoonshineSharedCore as well, since the source of MoonshineSharedCore linked as class path. This option help searching through the trail of the particular project.

**Comment by rat-moonshine** [comment]
Now one can select a project from the given dropdown of projects. 

Re-opening the 'search in project' window shall auto-select the project (in dropdown) from the last search event (if any); Else it'll auto-select the dropdown based on current selected project in sidebar.

I'm closing this as resolved, please reopen, if any bug found.

**Comment by JoelProminic** [comment]
To me, it seems more logical to have the dropdown default to the currently selected project each time you open the project search window.  This would still satisfy @piotrzarzycki21's request of being able to see the project that will be searched.

That said, saving the last setting would be more consistent with the behavior of the other search fields.  Do we want to value that consistency over our opinion on the above behavior?

I noticed that "Enclosing Projects" has been moved to be a checkbox.  Was this intentional?  If so, how does the "Enclosing projects" option behave in combination with the other two options.
![image](https://user-images.githubusercontent.com/24532731/36177470-57d9b99e-10db-11e8-8590-33d609d3a1ed.png)

**Comment by rat-moonshine** [comment]
Moving 'Enclosing projects' to a checkbox is intentional, and it is directly related to the 2nd option from _Scope_ - **Selected project**.

Where **Workspace** option search through all the opened projects at sidebar, Selected project does start its searching by the selected project to the dropdown; AND further moves to the 'Enclosing projects' option (which is optional).

'Enclosing projects' option works against a project. Having the option selected, search continues through all the external project directories/source mapped to the dropdown selected project's "Settings/Paths/Class Paths" section, as well. That means, if you have selected MoonshineDESKTOPevolved to the above said dropdown, it'll also search to MoonshineSharedCore - as MoonshineSharedCore source mapped to the MoonshineDESKTOPevolved's class paths section. This helps to continue a trail of searching starting from a particular project and whichever source is related to that particular project.

**Comment by rat-moonshine** [comment]
> That said, saving the last setting would be more consistent with the behavior of the other search fields. Do we want to value that consistency over our opinion on the above behavior?

Since this was one preferred enhancement requested by @piotrzarzycki21 , please give your opinion on @JoelProminic 's.

**Comment by JoelProminic** [comment]
"Enclosing Projects" is not a good name to describe this.  I discussed some options with @devsena today:
- "Include dependencies" - this is a bit vague, but it is more high-level
- "Include external sources"
- "Include additional source paths" or "Include external source paths" - Since this feature will only include the directories configured in the "Class paths" section (which corresponds to the <source-path> XML block), I think these are the most clear options

My preference is "Include external sourde paths", but I'm open to other ideas.

**Comment by rat-moonshine** [comment]
I agree that "Include external source paths" is more clear to its purpose.

**Comment by rat-moonshine** [comment]
> To me, it seems more logical to have the dropdown default to the currently selected project each time you open the project search window. This would still satisfy @piotrzarzycki21's request of being able to see the project that will be searched.
> 
> That said, saving the last setting would be more consistent with the behavior of the other search fields. Do we want to value that consistency over our opinion on the above behaviour?

@piotrzarzycki21 , please confirm on above thoughts from @JoelProminic so we can take a decision and can close this issue.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine sorry about that - I did miss it. Let's save the last setting - that seems to me logical.

**Comment by rat-moonshine** [comment]
The current behaviour follows the consistency (that found to other fields) to project dropdown list as well, when reopening the search dialog. @JoelProminic let me know if you want this to be change to the one you suggested - to select dropdown everytime based on sidebar selection only, I shall remove its auto-population code.

I'm closing this issue as resolved for now, please reopen it if found an issue.

**Comment by JoelProminic** [comment]
I'm fine with keeping the last value for now.  If you find that you feel differently after using this feature for a while (or we start getting complaints from other users), we can revisit this.
