### ISSUE TITLE
Apache Royale Project Build & Run Troubles

### ISSUE THREAD

**Issue by jmfillman** [prominic/Moonshine-IDE#180]
Build or Build and Run as Javascript does not appear to complete. It does seem to try and build, but no apparent errors, other than trying to find the playerglobal.swc, which was not part of the Apache Royale 0.9.0 SDK. No files generated in the project src folder, other than the basic mxml file. This is just the sample hello world app created when creating a new project, with no changes made. Flex Browser Project (FlexJS) specifically as the project type. Below is the generated output when attempted Build and Run:

: Compiling TProject_0002
: SDK path: C:\Users\xxxxxxx\OneDrive\Software\ApacheRoyale\SDKs\0.9.0\royale-asjs
: MXMLJSC
: -sdk-js-lib=C:\Users\xxxxxxx\OneDrive\Software\ApacheRoyale\SDKs\0.9.0\royale-asjs\js\bin\..\..\frameworks\js\Royale\generated-sources
: -load-config+=obj/TProject_0002Config.xml
: -compiler.targets=JSFlex
: C:\Users\xxxxxxx\OneDrive\Software\ApacheRoyale\SDKs\0.9.0\royale-asjs\frameworks\royale-config.xml(74): col: 0 unable to open 'C:\Users\xxxxxxx\OneDrive\Software\ApacheRoyale\SDKs\0.9.0\royale-asjs\frameworks\libs\player\11.1\playerglobal.swc'.
: C:\Users\xxxxxxx\OneDrive\Software\ApacheRoyale\SDKs\0.9.0\royale-asjs\frameworks\royale-config.xml (line: 74)
: 
:       </external-library-path>
: 
: 
: C:\Users\xxxxxxx\OneDrive\Software\ApacheRoyale\SDKs\0.9.0\royale-asjs\frameworks\royale-config.xml(98): col: 0 unable to open 'C:\Users\xxxxxxx\OneDrive\Software\ApacheRoyale\SDKs\0.9.0\royale-asjs\frameworks\libs\player\11.1'.
: C:\Users\xxxxxxx\OneDrive\Software\ApacheRoyale\SDKs\0.9.0\royale-asjs\frameworks\royale-config.xml (line: 98)
: 
:       </library-path>
: 
: 
: 2.364106576 seconds

**Comment by piotrzarzycki21** [comment]
Hi @jmfillman ,

Couple of questions:
1) What version of Apache Royale are you using - JS, SWF or JS only ?
2) Did you use "Flex Browser Project (FlexJS) during creation of project?

If you want to use Royale you should choose during project creation from drop down list:
![image](https://user-images.githubusercontent.com/24554795/36015286-2aca079e-0d6e-11e8-89d8-57057f0c64f8.png)

**Comment by jmfillman** [comment]
HI @piotrzarzycki21 

In response to your questions:

1) The SDK I downloaded was JS and SWF (apache-royale-0.9.0-bin-js-swf.zip)
2) Yes, I did select the Royale Browser project. Just tried it again to be sure, with the same result

Not sure that it matters, but even through I have Default SDK as Apache Royale, it does not default when creating a new project. I have to click on "Change" and then select it, when creating a project.

**Comment by piotrzarzycki21** [comment]
@jmfillman ,

Here is how things looks like. If you download **apache-royale-0.9.0-bin-js-swf.zip** - you are obligated to download Flash dependencies on your own. Player global and Adobe Air. In downloaded by you package there is ANT script called "InstallAdobeSDKs.xml" - it is helper which is showing you what kind of things you need to download in order to use that version of Royale.
If you are not going to build your application to SWF, but only to JS - please download [Apache Royale JS only](http://www.apache.org/dyn/closer.lua/royale/0.9.0/binaries/apache-royale-0.9.0-bin-js.zip) - you won't need in that case any kind of dependency and you will be able to build your applications to JavaScript only. - Try and let me know.

**Default SDK:**
If you have setup SDK in File -> Settings -> Default SDK - it is enough! Once you are creating the project - you have option to add some custom SDK specified for created project. 
Imagine situation when you have 3 projects open - two of them is Royale and one of them is Flex. Two projects will use default sdk setup in menu File -> Settings and one of them will need to have own Custom SDK - setup in right click -> Settings on the project.

Are you Windows or Mac user ?

**Comment by piotrzarzycki21** [comment]
Instruction for [Moonshine and Royale](https://github.com/apache/royale-asjs/wiki/Moonshine-IDE)

**Comment by jmfillman** [comment]
Using Windows 10. Using the JS only version of the SDK worked. No current plans for SWF use.

Thank you!

**Comment by piotrzarzycki21** [comment]
I'm glad! We will have new Moonshine 1.9.0 version released by Monday where Royale is fully supported, no additional tweaks etc. :)
