### ISSUE TITLE
Using Greensock Plugin

### ISSUE THREAD

**Issue by apintex** [prominic/Moonshine-IDE#183]
I want to use Greensock Plugin and after compiling without any error, when I run the application I get the following error: 
Error #1065: Variable com.greensock.plugins::TweenPlugin is not defined.
at global$init()[.../src/app.as:44]
(see attach file)
![captura de ecra 2018-02-12 as 16 31 19](https://user-images.githubusercontent.com/6188954/36107530-4cc24518-1012-11e8-9c86-17b95da0e4c5.png)

Same code in Flash Builder is ok!
Best regards, 
António Pinto

**Comment by piotrzarzycki21** [comment]
Hi @apintex ,

Could you show some screenshots from project configuration ?
I'm not familiar with that plugin - What SDK are you using ?

**Comment by piotrzarzycki21** [comment]
@apintex ,

Here is how I configured project with that library. I'm not sure if it's correct. I took library from [here](https://github.com/greensock/GreenSock-AS3).

1) Created new Adobe Air pure AS3 project - Tab **Home** -> **ActionScript Project (SWF, Desktop)**
2) Since it is not SWC I have added that library as source code: Right click on project -> **Settings** -> **Paths** I have added path to the src of that library.

![image](https://user-images.githubusercontent.com/24554795/36114910-b62e640e-1031-11e8-9050-f1e4dba07bcd.png)

3) I have never used that library so I took from your screenshot some code. My application looks like that and it's running without the problem.

```
package
{
    import flash.display.*;
    import com.greensock.plugins.TweenPlugin;
    import com.greensock.plugins.TintPlugin;

	TweenPlugin.activate([TintPlugin]);
	
	public class NewActionScriptProject extends Sprite
	{
		public function NewActionScriptProject()
		{
			super();
		}
	}
}
```

Let me know if your setup looks similar. I have used Apache Flex 4.16.1 with Adobe Air 28.0

**Comment by piotrzarzycki21** [comment]
@apintex did you try play with it again ?

**Comment by apintex** [comment]
Hello Piotr,

Sorry, I'm working on another project right now, but I've tested your solution right now and it's working.
I also tested with the compiled lib "greensock.swc" and it works.

Thanks for your help

Regards,

António Pinto
apintex@gmail.com

**Comment by piotrzarzycki21** [comment]
Thank you for reporting back! :)

Piotr
