### ISSUE TITLE
Jump to function/class definition doesn't work in conditional compiler constant

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#185]
If I have following conditional code:

```
CONFIG::MOONSHINE
{
    var myObj:CustomVO = new CustomVO();
    myObj.makeSomething();
}
```

I'm not able to jump to the definition of method by CTRL + Click. The same code is working outside conditional variable.

**Comment by piotrzarzycki21** [comment]
Hi @joshtynjala ,

I did check that issue in VSCode also and I cannot jump to the file either there. I'm attaching small example configured with VSCode with latest extension 0.9.1 and Moonshine.

[CompilerConstantsTest.zip](https://github.com/prominic/Moonshine-IDE/files/1728511/CompilerConstantsTest.zip)

**Comment by joshtynjala** [comment]
Is CONFIG::MOONSHINE set to false?

**Comment by piotrzarzycki21** [comment]
Yes it was set to false, but in VSCode I did have it to true.

**Comment by joshtynjala** [comment]
Just to be sure that I understand you, Ctrl+Click does not work when CONFIG::MOONSHINE is true?

**Comment by piotrzarzycki21** [comment]
Exactly!

**Comment by joshtynjala** [comment]
That's interesting. It definitely won't work when CONFIG::MOONSHINE is false because the compiler completely ignores that code. However, it should work when CONFIG::MOONSHINE is true.

Does completion work when CONFIG::MOONSHINE is true?

**Comment by piotrzarzycki21** [comment]
I would say no. It shows completion list, but I don't see there items associated to the object.

Having this code:
```
CONFIG::MOONSHINE
{
    var cls:MyTestClass = new MyTestClass();
    cls.testMethod();
}
```
When I type `cls.` I'm seeing hundreds of items, instead of couple of methods including one from the class.

If I do the same outside tag it's working great.

**Comment by joshtynjala** [comment]
Alright, I'll take a look!

**Comment by joshtynjala** [comment]
@piotrzarzycki21 The VSCode test project was not working correctly because you accidentally added `define` outside of the `compilerOptions` section in *asconfig.json*. When I move `define` to the correct location, I can successfully Ctrl+click on the method.

In Moonshine, a limited subset of compiler options are passed to the language server. I think the idea was to pass only the ones that actually affect code intelligence, and `define` may have been accidentally omitted from the list. I'll check it out.
