### ISSUE TITLE
Flex Browser Project build error

### ISSUE THREAD

**Issue by nihavend** [prominic/Moonshine-IDE#207]
Using moonshine 1.10.0
With the wizard created project (SWF).

(Artifacts of royale-asjs #505 ) sdk:Apache Royale 0.9.3 FP 11.7 AIR 14.0 (JS, SWF) 
path : D:\dev\Apache Royale\apache-royale-0.9.3-bin-js-swf\royale-asjs

when building project : 

: Compiling NewFlexBrowserProject
: Sending to mxmlc: mxmlc -load-config+=obj/NewFlexBrowserProjectConfig.xml -optimize=false -debug=true -o bin-debug/NewFlexBrowserProject.swf
: Error: Unable to access jarfile D:\dev\Apache Royale\apache-royale-0.9.3-bin-js-swf\royale-asjs\lib\fcsh.jar

How can i fix the issue ?

**Comment by piotrzarzycki21** [comment]
Hi @nihavend ,

Why are you trying to build Flex project using Royale ?

**Comment by nihavend** [comment]
I should have misunderstand things. Is not royale capable of generating swf file ? What does swf at the and  apache-royale-0.9.3-bin-js-swf stands for ?

**Comment by piotrzarzycki21** [comment]
Apache Royale is capable generating SWF, but not using code base written in Flex. You need to have code in Royale. Look into old resources [How it Works](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=34013930) section  - it still true for Royale.
Flow:
1. You are writing code using all resources which Royale provides, using AS 3 and MXML
1. Code can compile to SWF and JS

Note one thing not always application build to SWF will look same as in JS, because we (SDK developers) simple do not care to much about SWF part anymore. There also modules which do not have at all SWF parts - It's [MDL](https://github.com/apache/royale-asjs/tree/develop/frameworks/projects/MaterialDesignLite) module - It will fail if you wanted to build application which using that module to SWF.
