### ISSUE TITLE
Mouse Wheel Scrolls Both Sidebar and Away Builder Editor

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#217]
I encountered this issue related to #89 while testing #215.
1. Open an AWD file
2. Expand enough projects so that the scrollbar appears in the Projects sidebar
3. Scroll with the mouse wheel.  The sidebar scrolls and the image zooms as well. 
4. Open a text editor tab
5. Scroll the mouse wheel in the Projects sidebar
6. Return to the Away Builder tab.  The zoom has changed

**Comment by rat-moonshine** [comment]
I couldn't able to reproduce the problem#3 where mouse-wheel at sidebar area affects both the scroll to the sidebar and the opened Away Builder editor (zoom). I have tested in both the platforms. I also noticed that Away Builder's zoom level only changed by mouse-wheel when the mouse cursor is over the 3D editor area. I'm not sure if any other activities could reason the behavior in your case, @JoelProminic .

However, I have noticed one behavior:

- Open ABCD.awd file
- Change its zoom level by mouse-wheel or by the zoom buttons (at bottom)
- Open many other editors so the Away Builder disappears from the viewable tabs
- To appear ABCD.awd file again as displaying tab double-click on the ABCD.awd file again
- Away Builder tab activates again and the editor's zoom level changed/restored

The above behavior is expected, though. Since the opened awd file had no changes but only its zoom level, open call of a new awd file just replace the current editor stage without any notification. Since the new opened file replaced the current editor stage, its original zoom level also restored to the stage. 

Perhaps, I can force not to replace anything if the same file exists in the editor and has not changed, by some checks.

**Comment by rat-moonshine** [comment]
I able to reproduce the scroll behavior when I returned to the opened Moonshine editor after some work in other applications, and I noticed scrolling sidebar also changes Away Builder's zoom level. However, I'm having problem triggering the behavior again after a restart.

**Comment by rat-moonshine** [comment]
Okay, I able to reproduce the scroll behavior constantly by following steps:

- Make sure you have scroll to the sidebar
- Double-click any awd file to open
- **IMPORTANT** - do not move your cursor to the Away Builder's editor area, keep the cursor over sidebar until the file opened to the editor
- When file opened to the editor, drag the sidebar scroll or mouse-wheel over the sidebar only - this changes the Away Builder's zoom level
- Once moved the cursor to the Away Builder's editor stage, mouse-wheel on sidebar do not changes the Builder's zoom level anymore

Looking for a fix.

**Comment by rat-moonshine** [comment]
- Measure taken against unexpected mouse-wheel zoom level change based on above observation
- Not forced to open/replace 3D editor with file if the same same file already opened to the editor and not modified

Please, check.
