### ISSUE TITLE
Add ability to add/remove columns in DataTable along with edits "value"

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#228]

**Comment by piotrzarzycki21** [comment]
@rat-moonshine feel free to add more description or change the title

**Comment by rat-moonshine** [comment]
> 9. BUG: the value for the second column is cleared
- Fixed. 

> 11. Try to select text by dragging the mouse. BUG: Instead, the row is dragged, and when you release the mouse button, the row leaves edit mode.

I noticed that the property editor's list component (which was copied from another property editor file) already has some item drag enabled codes. However, there was no handler codes against the drag/drop feature. Discussing this with @piotrzarzycki21 , I came to a feeling that Josh added the drag enabling codes to one of the the original property editor class but probably it left unfinished. I moved forward and added requisite codes to update the columns based on item reordering by drag-and-drop feature. 

While doing the above fixes, I come up by many other UI issues as well. i.e. list scrolling issues (different results between me and Piotr's tests), odd scrolling issue when there are many items to the list even after the new fix applied, strange component jumping issue etc. 

I choose to use more generic DataGrid component instead of the List with custom renderer component this time. This actually worked out good. Using grid component also allowed us to have label to the columns (one that pointed by Joel, point.5). 

Please, check.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine after your changes to DataGrid - do you still need to use GenericUtils.listScrollToBottom ?

**Comment by rat-moonshine** [comment]
No. `GenericUtils.listScrollToBottom` is now only using to the TabForm. Please, check my email reply on this. We shall decide on this in coming time.

**Comment by rat-moonshine** [comment]
Archiving mockup for future referencing. 

![xcode referencing](https://user-images.githubusercontent.com/24370870/38803371-9e668914-418c-11e8-9ad8-3086720df93f.png)
![moonshine proposed steps](https://user-images.githubusercontent.com/24370870/38803375-a2d1f4c0-418c-11e8-931e-b944431d1ac1.png)
