### ISSUE TITLE
Tooltips and code suggestions not working with FlexJS nightlies for 0.9.0

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#23]
When I hover over a tag, following shows in stack trace panel

: Unknown tag:compiler.fxg-base-class

According to the problems panel this occurs at flex-config.xml (line 127)

Problems panel also shows - A fatal error occurred while checking for errors.

But this project is just Hello World from the sdk.examples and was working fine. I can still compile and run it with no issues.

Doug

**Comment by joshtynjala** [comment]
Moonshine currently isn't compatible with nightly builds of FlexJS because the nightly builds include this new fxg-base-class compiler option that didn't exist in 0.8.0.

A temporary workaround that has worked for users of VSCode (which shares the language server with Moonshine) has been to modify flex-config.xml to remove the line in question. This should also work with Moonshine.
