### ISSUE TITLE
Moonshine Does Not Open FlexJS Application in Browser

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#26]
I noticed that Moonshine was able to compile a project as either an SWF or as Javascriptt, but did not open the generated index.html in the browser after the build had completed
1. Open Moonshine
2. Create a new FlexJS project
3. Set a FlexJS SDK in the project settings
4. Select Project > Build & Run
5. Moonshine reports "Project Build Successful" on the console, but it does not open the project in the browser.
4. Select Project > Build & Run as Javascript
5. Moonshine reports "Project Build Successful" on the console, but it does not open the project in the browser.

When I tested with a Flex SWF project, the project opened properly in the browser.

I'm testing with the 1.6.0 release candidate, build 62, on Mac OS 10.10.3

**Comment by piotrzarzycki21** [comment]
@JoelProminic ,

I couldn't reproduce that issue on my PC. 

**FlexJS:**
However once someone create new FlexJS project and use first "Build & Run" end up with build were will be produced "swf" only application. 

In that case we are trying to launch pure swf file.

On my PC swfs are associated to "[Flash Player projector](https://fpdownload.macromedia.com/pub/flashplayer/updaters/27/flashplayer_27_sa.exe)" (standalone application) and built application is launching without the problem.

**Flex:**
In case of Flex application built application has html wrapper which launch swf - Moonshine is launching that html wrapper.

I did found one issue in a function which returns path to file which we are going to launch after the build and just pushed the fix.

**Question:** Do you have associated any application which is able to open "swf" file when you double click on it ?

**Comment by rat-moonshine** [comment]
I able to reproduce this problem again. By again I means I have found this problem before - https://github.com/prominic/Moonshine-IDE/issues/22. But I couldn't able reproduce this again during my tests at that time.

Now when I tested again, I see older FlexJS apps opening good with their corresponding 'index.html' wrapper (after build done) but the new projects. Investigating.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I see following pattern. If you run Moonshine and do "Clean project" and "Build & Run" your project will open always using "swf" - even if you later run "Bild & Run as Javascript".

It is probably cause in both MXMLCPlugin and MXMLCJavaScriptPlugin we have in function "testMovie" line:
`if (!pvo.htmlPath) pvo.getHTMLPath;` .

It means that once you set htmlPath for the first time it will never change for running built application. - please check whether we need that condition.

Additional think is that "getHTMLPath" has wrong name - it's not only retrieve path for us, but it also set to field "htmlPath" something. In my opinion this function should be called "refereshHtmlPath" - consider renaming in the next release.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 Yes, the problem was in getHTMLPath() method. I've committed requisite changes to fix this file opening problem in FlexJS. 

Note, all the new projects will be affected by this new changes. Older projects may continue to load .swf instead of .html when run the application. This is because Moonshine reads last saved value from project's configuration file. To change this,

- Right-click on project and choose `Settings`
- Go to `Run` section
- Do requisite changes to `URL to Launch` field to open appropriate wrapper HTML file (an example as follows)

![image](https://user-images.githubusercontent.com/24370870/30796657-a6facbf8-a1f0-11e7-8c69-29b22708bd20.png)

**Comment by JoelProminic** [comment]
Testing with today's build, I found that the application opened in my browser automatically after a Javascript build, but not after an SWF build.   I tested with a Flex Browser project as well, and I found that Moonshine did not open the compiled SWF.

@rat-moonshine was able to reproduce this behavior on Mac OS, but not on Windows

@piotrzarzycki21, I see that SWF files are set to open with Firefox (my default browser) by default on my workstation.  I was able to open the SWF in a browser window (though it did not show any text for some reason).

**Comment by JoelProminic** [comment]
I also noticed this behavior when testing with today's build:
1. Create a new FlexJS project
2. Set the custom SDK to FlexJS 0.8.0
3. Project > Build & Run as Javascript
4. The project builds and opens properly in the browser:
5. Project > Build & Run
6. The project builds to /<path-to-project>/bin-debug/TestFlexJS_0925.swf
7. BUG:  The Javascript page opens instead:  file:///<path-to-project>/bin/js-debug/index.html
8. Project > Clean Project
9. Project > Build & Run
10. BUG:  The application does not open in a browser

It sounds like Moonshine might be trying to launch the Javascript build every time, but it only works if the Javascript artifacts were already generated.

**Comment by rat-moonshine** [comment]
After some changes "Build & Run" now tries to open the SWF, instead of `bin/js-debug/index.html`. However, the `navigateToURL` method seems failing in OSX sandbox when it's something different than a valid HTML type of file (i.e. index.html). 

I see following pattern with the navigateToURL usage in OSX:
- The API able to open different types of file to browser (i.e. swf, html etc.) with the file type pattern "file:///Users/devsena/myFile.swf"
- The API able to open .html type of file from local-system to browser in sandbox application
- The API failed to open .swf type of file from local-system to browser in sandbox application

This problem noted in sandbox OSX environment only.

**Comment by rat-moonshine** [comment]
I seen we had the concept to open the project SWF (in case with **Build & Run** for browser based projects) with their corresponding wrapper HTML file. We have the related HTML wrapper template files also, supplied with the project templates, for this purpose. I can vaguely remember we worked on this wrapper html concept to overcome this `navigateToURL` issue only (probably in OSX mainly).

When projects are creates, its _bin-debug_ folder populates with the wrapper HTML files as well. But I noticed the current source continue to open .swf file instead of the .html in _bin-debug_ folder, I don't remember when or why we make this changes.

Opening the wrapper .html file with `navigateToURL` seems solves the problem in OSX sandbox. 

However, there is other test case which needs to work on. When user do a **Clean Project** call, all the files inside the _bin-debug_ folder deletes, including the wrapper HTML files. 

Those files never gets back again when you recompile the project. We need to restore those template files again after a clean project call, during compilation. I'm working on it.

**Comment by rat-moonshine** [comment]
Moonshine again starts reusing HTML wrapper template files in case of browser (.swf) projects.

To streamline the procedures better, a new `html-template` folder introduced to the web project templates:
- Following the Flash Builder way, Moonshine will accompany web projects with new `html-template` folder
- `html-template` folder will hold HTML wrapper template files to be use in the project's `bin-debug` folder, to run the compiled .swf file within
- The `html-template` files will be in use if user deletes the files inside `bin-debug` folder using **Clean Project** command
- Moonshine will restored the wrapper HTML template files from `html-template` to `bin-debug` folder, during project re-compilation
- In case of Flex or FlexJS .swf compilation (**Build & Run**) Moonshine will use the wrapper HTML file from `bin-debug` to open the project in browser
- If no `html-template` folder found in any project, Moonshine will alert the same and try to open the compiled .swf file instead with `navigateToURL` command

**Comment by rat-moonshine** [comment]
Few things to investigate on - found after tests in OSX:
- SWF compiled with FlexJS SDK coming blank (without any content)
- Wrapper HTML files to run the SWF, do not opens properly in OSX Moz and Chrome

**Comment by piotrzarzycki21** [comment]
@rat-moonshine ,

That may be the problem with web browsers itself. Can you try to open build SWF by [Download the Flash Player projector](https://www.adobe.com/support/flashplayer/debug_downloads.html) and see whether it displays anything.

**Comment by rat-moonshine** [comment]
I started testing HTML wrapper file behaviour in multiple OSX browsers, they are listed as below:
- Safari 11.0
- Chrome 61.0.*
- Mozilla 56.0
So far by my tests, Mozilla shown most problematic behaviour at this moment.

Moonshine uses default wrapper HTML that comes with Flash Builder web project. It uses same other elements (js, expressInstaller.swf etc.) files as well from the same bundle. 

When I ran the html in browsers, I see this icon in screen:
![image](https://user-images.githubusercontent.com/24370870/31065447-f8b4ecb8-a762-11e7-80aa-aafc9cf32542.png)

**Chrome and Safari**: Clicking on the icon - if higher version of Flash Player plugin already installed, it rans the SWF on browser.
**Mozilla**: Even I ensured I have higher version of plugin installed, it always taken me to the Flash Player downloader page, like its not able to detect properly if/which plugin version installed.

I tested by some alteration in the HTML, and I noticed that "activate content" type of option only comes when the files are hosted to some server. 

I uploaded the files to some test server, and here are the results:

Safari: ![image](https://user-images.githubusercontent.com/24370870/31065500-79518d68-a763-11e7-8988-ef0bc5655413.png)

Chrome: ![image](https://user-images.githubusercontent.com/24370870/31065524-92037574-a763-11e7-83c9-82296b0e0cc0.png)

Mozilla: ![image](https://user-images.githubusercontent.com/24370870/31065532-a254c572-a763-11e7-9168-269f31f1a692.png)

I'm not sure how we can enable that option when the files runs at local, though.

@piotrzarzycki21 any idea how we can do that?

**Comment by rat-moonshine** [comment]
Testing the 2nd problem - producing SWF with FlexJS SDK in OSX, always produce blank SWF. This visible in both browsers and in FP projector. 

Moonshine uses following code with _NativeProcess_ to produce the SWF in case of FlexJS SDK:
`export FLEX_HOME=/Users/[user]/Downloads/MoonshineSDKs/FlexJS_SDK/FlexJS_0.7.0_AIR_23.0&&export FALCON_HOME=/Users/[user]/Downloads/MoonshineSDKs/FlexJS_SDK/FlexJS_0.7.0_AIR_23.0&&/Users/[user]/Downloads/MoonshineSDKs/FlexJS_SDK/FlexJS_0.7.0_AIR_23.0/js/bin/mxmlc -load-config+=obj/NewFlexJSBrowserProjectConfig.xml -optimize=false -debug=true -o bin-debug/NewFlexJSBrowserProject.swf`
The above codes works well in Windows, however.

@piotrzarzycki21 this may need your attention.

**Comment by rat-moonshine** [comment]
During tests, we've found that blank SWF caused by the SDK version less than 0.8.

"Build & Run" with FlexJS 0.8 produced SWF that shows it's contents well.

After some investigation @piotrzarzycki21 discovered that using `bin/mxmlc` instead of `js/bin/mxmlc` produce good SWF with 0.7, too.

I've modified requisite codes in Moonshine build process to use `bin/mxmlc` when the SDK is less than 0.8 (FlexJS). This seems fixed the blank SWF problem with my tests.

**Comment by piotrzarzycki21** [comment]
Regarding: https://github.com/prominic/Moonshine-IDE/issues/26#issuecomment-333446261,

I believe that we don't have to much influence on web browser itself. It is user responsibility to click on activation link.

In case of Firefox I figure out that if you would like to launch application there - it need to be on the "server". Launching swf locally using wrapper won't work anymore. I put project on my localhost and firefox was able to display content. Here is the discussion on [Flex Users](http://apache-flex-users.2333346.n4.nabble.com/Can-t-Debug-From-Flash-Builder-tp15724p15744.html) mailing where Josh explaining what may be the cause of that issue. - I doubt that we can do anything more here.

**Comment by JoelProminic** [comment]
Here is the relevant comment from the thread that Piotr linked:

	
    This may or may not be related to your issue, but I figured I'd mention it.

    Since Flash Player 23, local-with-file-system permissions have been
    restricted. These file system permissions used to be applied when you use
    the -use-network=false compiler option. Now, you're required to use
    local-with-networking permissions, which don't let you access the local
    file system. If you need local file system access, you can add the SWF to
    Flash Player's trusted locations. Usually, Flash Builder's debugger will
    add any SWFs it loads to the trusted locations automatically.

    As a workaround, you can run a local server for debugging so that it loads
    from the "network" instead of from the file system.

    - Josh


I see a couple possiblities that we could investigate further:
- Adding the SWF to a Flash Player trusted location (or providing instructions for the user)
- Bundling a lightweight local server with Moonshine so that we can provide the SWFs by that method.  I'm not sure if Apple will let us do this, though.

When I did a quick test with the Trusted Locations, they did not seem to make a difference for Firefox.  I tried specifying both the parent directory and the SWF itself:
![2017_10_02__trustedlocations](https://user-images.githubusercontent.com/24532731/31089368-5f3f8870-a769-11e7-9a6a-f5cca4afe042.png)

**Comment by piotrzarzycki21** [comment]
@JoelProminic ,

We have had long discussion with @rat-moonshine about possible solution and didn't come up with anything which could simple resolve that.

Giving your options for consideration:
> Adding the SWF to a Flash Player trusted location (or providing instructions for the user)
I did try it on Windows 10 and it didn't change anything as it on Mac.

> Bundling a lightweight local server with Moonshine so that we can provide the SWFs by that method. I'm not sure if Apple will let us do this, though.
Currently I'm not sure how can we implement such thing and I definitely share the same concerns that we will have problems with Apple stuff. I believe also having such external local server with Moonshine will generate to us some additional problems.

Some options:
1. "Remote debugging". - Application is pushed to the server and Moonshine is able to attach debugger into that application. - I believe this is totally new feature which is out of scope.
2. Partial remote debugging by using 3rd party software [Fiddler](http://www.telerik.com/fiddler). User in that case will have to push app to the server same as in (1). Moonshine have to be able to listen for the application, and Fiddler replacing runned on server swf request with local swf - That replacement triggers debugger.
3. Redirect user to use other browser than Firefox, since we don't have any clear and simple to use resolution for that. Everything above will generate additional problems in case of usage. I recommend go with that option. 

Please discuss it today with @rat-moonshine . In whatever direction we will go I believe that is something for not 1.6.0 release.

Thanks,
Piotr

**Comment by JoelProminic** [comment]
I think we should report this as a known issue for this release, and delay any Moonshine solutions for a later release.  Here is a rough draft.

    While testing for this release, we noticed that most browsers were blocking
    the user from opening SWFs from their local filesystem.  The browsers will
    show a message like "To view this page ensure that Adobe Flash Player
    version 16.0.0 or greater is installed." and a "Get ADOBE FLASH PLAYER"
    button.

    For most browsers, if you click the button, the browser will prompt you
    about whether you would like to allow the SWF to run.  After you allow
    this, you can run the SWF normally.  However, Firefox will direct you to a
    download page instead, so you may want to test in other browsers for now..  

    Alternatively, you can bypass the above errors by deploying the generated
    SWF to a local or remote server.

**Comment by piotrzarzycki21** [comment]
@JoelProminic ,

Should we put such section in our CHANGELOG file like "Known Issues" ?

Thank you for this draft!
Piotr

**Comment by JoelProminic** [comment]
I added my writeup to CHANGELOG.md.

I also created https://github.com/prominic/Moonshine-IDE/issues/36 so that issue could be closed for the 1.6.0 release.
