### ISSUE TITLE
Cannot close Home tab

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#262]
The close button on the Home tab appears to be incorrectly disabled.

I don't want it to add clutter to my tab bar.

**Comment by rat-moonshine** [comment]
The Home tab intentionally designed to remain open all the time, so user can return to the splash screen and choose from the given options. Thus, the close button also shows as disabled.

**Comment by JoelProminic** [comment]
There are a couple features that are only available on the Home page for now.
- RECENTS - this could be added in the menu
- FEEDBACK - From #12.  This was originally added to the Home page so that it would be something that is regularly visible to the users.  
However, the user can bring back the Home tab with View > Home, so they would still be able to get to these features.

I'm fine with making this tab closeable, as long as it opens by default on startup.  This should show the user the FEEDBACK section while they are getting started with Moonshine, at least.

I think we should probably add the RECENTS section to the menu if the Home tab is closeable, but that should be tracked in a different issue.

**Comment by rat-moonshine** [comment]
- Home tab is now close-able
- Close All menu option adjusted with all other existing logic sets
- Home tab can bring back through View > Home

**Comment by joshtynjala** [comment]
Thanks!

**Comment by atingupta2005** [comment]
I tested it and confirm that:

1. The Home tab can now be closed using "Close" and "Close All" button and also the Home tab can be closed using the "X" icon on the Home tab itself.
2. The Home tab then can be reopened using the "View\Home" button
