### ISSUE TITLE
Global error notification system

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#268]
By this time, we've seen many cases were an exception/uncaught-error fall silently because a package application do not throw the way we used to see in a development/debug version. The exception therefore sometime creates a chain of event which break things here and there, which became difficult to point out.

We need a global error notification system for such uncaught errors to popup and notify with the errors. This will help to further find on the issue and do a fix.

**Comment by piotrzarzycki21** [comment]
In that case I definitely don't want to have any popup notification in face of the user. I would like to have see heavy usage of our console. 

The other option is to implement global notifications in UI where we will have nicely showing Tooltip - where we use errorString.

**Comment by rat-moonshine** [comment]
I don't have any immediate plan to show errorString to the UI when an exception may result in deep codes. Though, we can avoid popup. It's also sound valid to show the error in console. 

I would also plan to have some place in menu which should open-up an window listing any probable errors and probably have some input areas to detail the scenario when the error fired and post to us. For posting to server side, I may need to talk to @JoelProminic , though.

**Comment by JoelProminic** [comment]
I like seeing the errors on the console - I think this should be useful for our debugging.

Users can already submit bug reports to GitHub from Moonshine using the "I'm having some problems" button on the Home tab.  This form will open a page on GitHub to allow the user to create a new issue.   We could further improve this interface by automatically appending the recent error log (and version and OS?) to the generated issue text.  The user would have a chance to review and edit this information before it is submitted, so I don't think we need to worry about prompting the user if they want to include the log.

@rat-moonshine suggested that we add a link below each console error message that would allow the user to submit a bug for the error message.   In this case, we will want to specifically ask for context for the error in the prompt, so that we don't get an issue with only an error like:

    : Error: Error: Error #3001
    : 	at actionScripts.plugin.errors::UncaughtErrorsPlugin/uncaughtErrorHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at MethodInfo-14670()
    : 	at SetIntervalTimer/onTimer()
    : 	at flash.utils::Timer/tick()

**Comment by rat-moonshine** [comment]
I'm closing this issue as the basic functionality to report unhandled errors are now in place. We can further fine-tune the system after 1.13.0 release, with separate issue requests.

**Comment by piotrzarzycki21** [comment]
Please add information in Added about that feature.
