### ISSUE TITLE
Component include should display in property editor only file names with extension

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#289]
Currently Include display whole path in drop down list which is not much readable. I think we should change it to display file name only and full path in tool tip. 

![image](https://user-images.githubusercontent.com/24554795/40724514-82722f9e-6421-11e8-9a40-453d1c71afa3.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine please do not start working on that till I close #280

**Comment by piotrzarzycki21** [comment]
It's true that it can be a problem when you have two or three the same name for files, but now it looks really bad, because I don't seen file name at all.
I see only paths and I have to expand property editor. I doubt that showing relative path will change anything it is still will be too long. Not sure what to do with that.

**Comment by rat-moonshine** [comment]
I agree. Considering the panel width, it may needs extra effort to see full file name. 

I'm wondering, why do you are requiring to expand the property editor rather than scrolling the dropdown list only? Can you confirm if you can also get the horizontal scroll that I'm having (?)

![image](https://user-images.githubusercontent.com/24370870/40832005-0a7cd83a-65a8-11e8-9d7e-862a783a718e.png)

**Comment by piotrzarzycki21** [comment]
You are seeing file name once you expand and scroll list horizontally - That's not too much convenient.

Just come into my mind how could we resolve that issue. We could stay on the list with full path, but once you select element you should see only File name - What do you think ?

**Comment by piotrzarzycki21** [comment]
In order to stay with the idea that DropDownListForm is generic we could do following:

1. Implement `DropDownListWithLabelDisplayField` extend `DropDownList`
1. Introduce property labelDisplayField which allows display file name only or whatever value of property from object which user point.
1. `labelDisplayField ` allow display in `labelDisplay ` value for selected item using function `override mx_internal function updateLabelDisplay` - force what is displayed only if labelDisplayField exits. - take a look how that function is implemented.

**Comment by rat-moonshine** [comment]
It's done. Please, check.

**Comment by piotrzarzycki21** [comment]
It looks good but I would add also to DropDownList toolTip which will display full name of the file. I have following situation. When I roll over on DropDownList it would be great to have tooltip.

![image](https://user-images.githubusercontent.com/24554795/40919775-c32e4b34-680a-11e8-82c0-fee3482f04c6.png)

In `updateLabelDisplay` make `this.toolTip = labelDisplay.text;`

**Comment by JoelProminic** [comment]
Do we want to reduce the File Name value and dropdown values to just be like "index.xhtml"?   I had to expand the width of the sidebar significantly in order to be able to see the filename.  The full path could be displayed in a tooltip.
![image](https://user-images.githubusercontent.com/24532731/40947319-c1375808-6827-11e8-84a4-a33985ae4f92.png)

The disadvantage is that if the user used the same name but different directories for the XHTML files, the entries would all look the same without the tooltips.

Also note that the exported project (TestVisualEditorPrimefaces/TestVisualEditorPrimefaces_exported) is included in the File Name combobox, which is probably not desirable.

**Comment by piotrzarzycki21** [comment]
@JoelProminic In my opinion full path should be visible at least when we open drop down list. Following rules should be applied for sure:
1. Drop down list should display tooltip as I described it above 
1. Each item when it's selected/truncated/roll over (whatever) when list is opened should display tooltip
1. To be more convenient maybe we should scroll horizontally maximum to the right when user open up the drop down list? That's avoid the need of expanding that area. User will expand it only if would like to see full path - however option two also help with seeing full path, because we will have tooltip on each element.

**Comment by rat-moonshine** [comment]
Okay. Here are few things which I have updated today. 

1. While looking into how the xhtml list label were populating - it was populating in this format: 
`[ProjectName]/src/MyFile.xhtml`
The xhtml resource list was fetching using existing Moonshine command that we used in **Find Resource** section. In Find Resource section, having the `[ProjectName]` as prefix to the resource path/name was handy when there are more than one projects opened at a time. This is also the same format that we found in Flash Builder resource search section. But in current context (Include), I found having `[ProjectName]` as prefix is taking some more of the horizontal scroll which we can deduct. So I have made some modification to the Moonshine method and the populating dropdown list now shows labels without `[ProjectName]` as prefix but only the relative path to a file. 

2. As @JoelProminic reported that an exported project's .xhtml files also get added to the Include dropdown list which is wrong. Using the Moonshine's existing **Find Resource** parse method, it was looking through any folders starting from the project's root. I made some modification to this method as well, now it'll return files starting from the project's source folder in case of Include.

3. To eliminate horizontal scroll possibility as much as possible, I'm now showing only file name to the dropdown list (when its open/close) and relative path to the rows' tooltip. This can be changeable to show relative path instead, please check.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine To me changes looks good. Are you planning to make something more? If not please close that one.

**Comment by JoelProminic** [comment]
Note that the tooltips currently show the same value as the combobox entries.   @rat-moonshine suggested that this could be useful if the path/name are long enough that that the full string is not visible, but otherwise this seems unnecessary and/or distracting.
![image](https://user-images.githubusercontent.com/24532731/41123971-136806c8-6a66-11e8-8e3b-24e95a198741.png)

**Comment by rat-moonshine** [comment]
I made some adjustment to make sure tooltip do not distract the view when it's not necessary (as above @JoelProminic pointed). From now on, tooltip will be available only when the list component has a horizontal scroll and having a tooltip is helpful to read the item path without being scrolled.
