### ISSUE TITLE
"Set as Default" is broken

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#306]
[BUG]

**Comment by rat-moonshine** [comment]
This is now fixed.

**Comment by piotrzarzycki21** [comment]
Function `checkFileExistenceAndReport ` is being used in method `read ` and now it's used in several other places. `read` itself is used 27 times in app. Maybe this is a good scenario to do not bother user by Alert, but rather put error on the console, that real error, because in current implementation we are not doing that. That's our custom message. 
If you were able to reproduce that issue and put breakpoint let's say in `read` in `catch` - Do you get real error ?

**Comment by rat-moonshine** [comment]
We anyway have a try/catch in `read()`, but that doesn't prevent us from throwing uncaught error from the File API, unfortunately.

Personally, I don't like to show a full stack of error details to the user rather a customized error (which is yes our message) in this case. Regarding showing off the alert, as I have mentioned an console output can easily overlook (i.e. console is collapsed) but alert is more direct. But I'm open for opinion against this.
