### ISSUE TITLE
Error with Visual Editor Files with Same Name but Different Directory

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#308]
While testing #302, I noticed a strange behavior when working .xhtml files with the same name in diferent subdirectories of the project.
1. Create a new PrimeFaces Visual Editor project.  The xhtml files are stored under src/main/webapp
2. Create two xhtml files with the same name, in different directories.  For me, this was foo/index.xhtml and bar/index.xhtml.
3. Close both files, if they are open
4. Open foo/index.xhtml, add a label showing "Foo", and save
5. Open the bar/index.xhtml.  BUG:  it shows the same contents
6. Modify the label in bar/index.xhtml to "Bar", and save
7. Close and reopen foo/index.xhtml.  BUG:  The contents have updated to match the second file
8. Close both files
9. Open foo/index.xhtml.  The label is still "Bar"
10. Close foo/index.xhtml
11. Open bar/index.xhtml.  The label is still "Bar"
12. Check the filesystem.  foo/index.xhtml shows "Foo", while bar/index.xhtml shows "Bar"
13. Check visualeditor-src.  Both of the files are saved to visualeditor-src/index.xhtml

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed fix. Try newest build from bamboo. Note that if you have currently some project which does have files under some folders - it may no longer work. This is because files created in `visualeditor-src\main\webapp\` were created in a wrong location. 

If you created src\main\webapp\foo\index.xhtml in visualeditor-src\main\webapp\index.xml - which was incorrect.
