### ISSUE TITLE
Integrate Josh' ActionScript debugger to Moonshine

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#31]
Integrate Josh' debugger update codes from https://github.com/joshtynjala/Moonshine-IDE to production Moonshine repository.

**Comment by rat-moonshine** [comment]
I able to manage the initial requirement to debugger line highlighting to Moonshine. Following things were managed until this period of time:
- New debugging line highlighting in place, which is different than the usual line selection in editor
- Debugger line highlighting stays to its position during editor scrolling (it kept vanishing or shown unexpected behavior over scrolling before)
- Line highlighting is pointing properly over playhead change after Step Over or Play

There are still things to work on:
- Debugger highlighting needs to be removed once the debugger session completes its cycle
- Debugger Variables section tree component needs to reskin to look more proper (as we used to see in an IDE debugger) - at this moment it's only showing with basic folder icon and markers

**Comment by rat-moonshine** [comment]
I've updated Moonshine debugger with following changes:
- Debugger highlighting now removes when debugger session is over (i.e. Stop, Play to end)
- Debugger highlighting removes from the last highlighted file when playhead jumps to a new class/file
- Debugger highlight footprints removes properly so it does not leave any UI trace while scrolling
- Some UI tweaks
- "Variables" sections icon modified replacing regular folder leaf icons

**Comment by JoelProminic** [comment]
When I did some testing on this today, I noticed some issues with the highlighting.  If these issues are not easy to resolve, then we should consider moving them to a later release.


When I click in the left column to set a breakpoint, the text in that row is automatically selected:
![2017_10_02__debug_highlighting selected](https://user-images.githubusercontent.com/24532731/31095245-cc405c24-a77d-11e7-9ff2-3961beaa9171.jpg)


Then if I run the debugger, the application stops on that row but the highlighting does not change, as shown in the screenshot above.

I don't think the row should be automatically highlighted when setting a breakpoint.  Is related to some other feature?

Having the debugging highlighting be obscured by the selection highlighting is annoying in this case, but I'm not sure if I will be a problem after the above issue is resolved.   If it is still a noticable problem, we could consider using a different color for text that is both selected but also the current line for the debugger.


I also noticed that the debugger will automatically scroll to put the current line at the top of the page.  For example:
1. I start the debugger for an application
2. It hits a breakpoint
3. The current line is displayed at the top of the page.
4. Scroll up a bit to see the context for the line
5. Click "Step Over"
6. The current line is displayed at the top of the page, so I can no longer see the context.

When the "current" line is not visible currently in the window, the putting it at the top of the window seems like a reasonable default.  Perhaps it would be better to put it in the middle of the window or a few lines below the top so that it is easier to see some of the context.


When the debugger highlights a line with a string, the text becomes very hard to read:
![2017_10_02__debugger_contrast](https://user-images.githubusercontent.com/24532731/31095235-c51d5c1c-a77d-11e7-9675-0bf3b1796a6f.jpg)



I noticed that highlighting doesn't seem to work properly when opening files:
1. Set a breakpoint
2. Debug > Build & Debug
3. Close all editor windows.
4. Trigger the breakpoint.  The editor opens, but the current line is not highlighted, and the window position is not set normally.
5. Close the editor 
6. Click "Step Over".  The editor opens, but the current line is not highlighted, and the window position is not set normally.
7. Click Step Into for a line that will reference another unopened file.  The editor opens, but the current line is not highlighted, and the window position is not set normally.

**Comment by JoelProminic** [comment]
Each time I have the Debugger continue (i.e. Run, Skip Over), it collapses the Variable tree.  

If this is not trivial to fix, then it can be moved to a later release.

**Comment by JustinProminic** [comment]
- Debug highlight color changes to soothing one increase text readability
- Debug highlight now showing over existing line selection

**Comment by rat-moonshine** [comment]
- Debug highlight color changes to soothing one increase text readability
- Debug highlight now showing over existing line selection

**Comment by piotrzarzycki21** [comment]
@rat-moonshine ,

I just pushed fix for the issue where debugger jump on the top of the page with selection. I have made following rules:
1. Content will not scroll if debugger breakpoint is visible on the screen
2. Content will scroll to the half of the scrollable page if breakpoint is visible - 

In case (2) I did add some offset for the scroller vertical possition - That offset do not have to be correct. My tests went well. Let me know how it look like with scenario (2).

**Comment by rat-moonshine** [comment]
Scrolling issue is now looks nice. Thanks @piotrzarzycki21 . 

Following fixes also applied:
- In case of a file having breakpoints and not opened, when debug starts Moonshine auto-opens the file and properly highlights the first breakpoint instance also
- Clicking on line number do not auto-selects the line anymore

**Comment by JoelProminic** [comment]
@piotrzarzycki21

While testing today, I noticed that your rules worked properly for the main class of a project:
> I just pushed fix for the issue where debugger jump on the top of the page with selection. I have made following rules:
> 
> 1. Content will not scroll if debugger breakpoint is visible on the screen
> 2. Content will scroll to the half of the scrollable page if breakpoint is visible -
> 
> In case (2) I did add some offset for the scroller vertical possition - That offset do not have to be correct. My tests went well. Let me know how it look like with scenario (2).

If I use Step Over, the window position shifts to that the highlighted line remains in the center of the window.

I noticed that in the main class, Moonshine would not shift the window position for the first 3-4 steps, but then it started shifting the position with every step.  For other classes, the window position changed every time I clicked Step Over.  However, this is a minor discrepancy, and overall the behavior seems pretty intuitive.
