### ISSUE TITLE
Download a New SDK leads to Error #1009

### ISSUE THREAD

**Issue by joerg-rade** [prominic/Moonshine-IDE#326]
![screenshot 071 new issue prominic_moonshine-ide - mozilla firefox](https://user-images.githubusercontent.com/4637858/42679153-46672450-8681-11e8-9167-a648c43e5904.png)

## Environment
Windows 7, 64bit, behind a company fw/proxy

## Description
In Moonshine 1.13.0 I tried to 'Download a New SDK'

## Steps to Reproduce
Dialog to create a new JS/Royale project

## Expected Behavior
DropDownLists filled 

### Errors
Error #1009
TypeError: Error #1009
	at org.apache.flex.packageflexsdk.resource::ViewResourceConstants/update()
	at InstallApacheFlex/loadUSInEmergencyComplete()
	at InstallApacheFlex/loadLanguage()
	at InstallApacheFlex/selectDefaultLanguageInEmergency()
	at InstallApacheFlex/xmlError()
	at flash.events::EventDispatcher/dispatchEvent()
	at flash.net::URLLoader/onComplete()

**Comment by piotrzarzycki21** [comment]
@joerg-rade I think you should try install installer externally and download SDK. It will take time before we update internal one.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 , can you help me with the updated codes, it'll be then easy to incorporate with the existing one - unless the current applied changes are vast. But then anyway it'd be helpful if you list me the files which has the changes.

**Comment by piotrzarzycki21** [comment]
I will try to do that over the weekend or when I come back on Monday.

**Comment by piotrzarzycki21** [comment]
@joerg-rade I will reopen that one and we will update installer as part of that issue. I would be glad if you try that one. Not sure if it will be 1.14.0 release. We will see.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine This is the list of files changed:
[flex-installer/common/src/com/hurlant/util/Base64.as](https://github.com/apache/flex-utilities/commit/e09e191bfff548a469108142940c1081a5755892#diff-752361f7aca14c1ae129174c883bd9a2)
[flex-installer/common/src/com/hurlant/crypto/tls/TLSSocket.as](https://github.com/apache/flex-utilities/commit/e09e191bfff548a469108142940c1081a5755892#diff-f23cc344bbcab8f6ac8a6227e23b44fc)
[flex-installer/installer/src/InstallApacheFlex-app.xml](https://github.com/apache/flex-utilities/commit/e09e191bfff548a469108142940c1081a5755892#diff-3f6c92db6921d1a9a0a7ad97ca3d6113)
[flex-installer/installer/src/InstallApacheFlex.mxml](https://github.com/apache/flex-utilities/commit/e05c9bd8fed1324014868fff1012b0ade8587223#diff-b184ddad8e4a5c9bcdcd3deaaeb9c7c9)
[sdk-installer-config-4.0.xml](http://flex.apache.org/installer/sdk-installer-config-4.0.xml)

Let me know if you need something more.

**Comment by rat-moonshine** [comment]
Thank you @piotrzarzycki21 .

I've updated Moonshine SDK Installer lib with updated source. Compiled with AIR 28.0, let me know if it has any dependency to build with AIR 30.0.

Requesting to give a test.

**Comment by piotrzarzycki21** [comment]
It has to be build with AIR 30.0. Installer are using libs [common](https://github.com/apache/flex-utilities/tree/master/common) and [ant_on_air](https://github.com/apache/flex-utilities/tree/master/ant_on_air) - Those dependencies needs to be provided. 
How are you building ApacheFlexSDKInstallerLib.swc ?

**Comment by joerg-rade** [comment]
Hi Piotr, I did not build my self - just used the UI of moonshine. -j

**Comment by piotrzarzycki21** [comment]
@joerg-rade I didn't mean that you have to build yourself anything! :) I hope we will have fix in upcoming Moonshine 1.14.0. You can just use externally installer for now instead build one.

**Comment by santanu4ver** [comment]
> Requesting to give a test

Please, hold any test. I discovered some place which haven't been updated. 

> It has to be build with AIR 30.0. Installer are using libs common and ant_on_air - Those dependencies needs to be provided.

Requisite library dependencies are there. I've only built the requisite SWC that used to in-build SDK Installer and to Moonshine App Store Helper with AIR 28.0.

**Comment by santanu4ver** [comment]
> @rat-moonshine Maybe in that case we will have to also switch Moonshine to Air 30.0 not sure.

In past, we've faced SDK download trouble for SDK > 28.0, we chose to build on 28.0 only so others can download until that version without any problem. If we won't have any download trouble for SDK > 28.0 then perhaps in next release we can plan for the latest SDKs. 

I have just commit the missed update to SDK Installer library, I shall also give a test some time soon if this works with 28.0 only.

**Comment by piotrzarzycki21** [comment]
The thing is that installer is require Adobe Air 30 or since installer itself in Moonshineis swc, so our Moonshine should use Adobe Air 30. Look into the explanation for that issue [here](http://apache-flex-development.2333347.n4.nabble.com/Discuss-Apache-Flex-SDK-Installer-3-3-2-RC1-tp65400p65405.html)

**Comment by rat-moonshine** [comment]
You see I'm not oppose of using most latest SDKs to Moonshine. I was only cautious on using a newer SDK when a release is at our door-step, and nothing breaks between Windows and OSX. 

But if the installer codes itself requires AIR 30.0 (I see Alex's reasoning of building 64-bit Windows installer, downloading 64-bit runtime etc. - but we're definitely not going to build any standalone installer for the Apache SDK Installer, and the library requires to share sandbox of Moonshine installer only), then we can give a try updating Moonshine to 30.0. If you think we should give this a try, then I've no problem if we're doing this, but considering the cautiousness I described.

**Comment by piotrzarzycki21** [comment]
When I'm running installer I'm getting following screen:
![image](https://user-images.githubusercontent.com/24554795/42766360-92351bc6-891a-11e8-8246-8c1080bf2c37.png)
I did choose Don't Update.

Next during SDK installation I got following error:
```
: Error #1034
: TypeError: Error #1034
: 	at org.apache.flex.xml::XMLTagProcessor/processChildren()
: 	at org.apache.flex.ant.tags.supportClasses::TaskHandler/execute()
: 	at org.apache.flex.ant.tags::Project/execute()
: 	at org.apache.flex.ant::Ant/processXMLFile()
: 	at InstallApacheFlex/runInstallerScript()
: 	at InstallApacheFlex/handleApacheFlexSDKZipFileUnzipComplete()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at org.as3commons.zip::Zip/loadBytes()
: 	at InstallApacheFlex/unzip()
: 	at InstallApacheFlex/uncompressApacheFlexSDK()
: 	at org.apache.flex.packageflexsdk.util::MD5CompareUtil/fileStreamOpenHandler()
```

Full log:
```
Installer path: C:\Program Files (x86)\MoonshineDevelopment
Installer version 1.14.0 (windows)
Available Memory: 56553472 (-bit)
Using Locale: en_US
Fetched the SDK download mirror URL from the CGI.
SDK version Apache Flex SDK 4.16.1
AIR version 30.0
Flash Player version 30.0
Creating Apache Flex home
Creating temporary directory
Downloading Apache Flex SDK from: http://ftp.ps.pl/pub/apache/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-bin.zip
Verifying Apache Flex SDK MD5 Signature
The Apache Flex SDK MD5 Signature of the downloaded files matches the reference. The file is valid.
Uncompressing: D:\Work\flex-sdk-test\temp\apache-flex-sdk-4.16.1-bin.zip
Finished uncompressing: D:\Work\flex-sdk-test\temp\apache-flex-sdk-4.16.1-bin.zip
Error #1034
TypeError: Error #1034
	at org.apache.flex.xml::XMLTagProcessor/processChildren()
	at org.apache.flex.ant.tags.supportClasses::TaskHandler/execute()
	at org.apache.flex.ant.tags::Project/execute()
	at org.apache.flex.ant::Ant/processXMLFile()
	at InstallApacheFlex/runInstallerScript()
	at InstallApacheFlex/handleApacheFlexSDKZipFileUnzipComplete()
	at flash.events::EventDispatcher/dispatchEvent()
	at org.as3commons.zip::Zip/loadBytes()
	at InstallApacheFlex/unzip()
	at InstallApacheFlex/uncompressApacheFlexSDK()
	at org.apache.flex.packageflexsdk.util::MD5CompareUtil/fileStreamOpenHandler()
Installation aborted: http://flex.apache.org/track-installer.html?failure=true&label=Apache Flex SDK 4.16.1&version=4.16.1&os=windows&installerversion=1.14.0&info=Error #1034
TypeError: Error #1034
	at org.apache.flex.xml::XMLTagProcessor/processChildren()
	at org.apache.flex.ant.tags.supportClasses::TaskHandler/execute()
	at org.apache.flex.ant.tags::Project/execute()
	at org.apache.flex.ant::Ant/processXMLFile()
	at InstallApacheFlex/runInstallerScript()
	at InstallApacheFlex/handleApacheFlexSDKZipFileUnzipComplete()
	at flash.events::EventDispatcher/dispatchEvent()
	at org.as3commons.zip::Zip/loadBytes()
	at InstallApacheFlex/unzip()
	at InstallApacheFlex/uncompressApacheFlexSDK()
	at org.apache.flex.packageflexsdk.util::MD5CompareUtil/fileStreamOpenHandler()

```

**Comment by piotrzarzycki21** [comment]
> Requisite library dependencies are there. I've only built the requisite SWC that used to in-build SDK Installer and to Moonshine App Store Helper with AIR 28.0.

What do you mean by saying that ? Is this mean that both libraries common and ant_on_air were build and you have used them in order to produce new Installer swc for Moonshine ?

**Comment by rat-moonshine** [comment]
I see the fix is much more complicated in implementation than I thought. 

Initially, I see this error (`TypeError: Error #1034`) was reasoned by `ApacheURLLoader` class, while loading a https URL, following one stream error while calling the URL - but I don't know why. I remember we had trouble with URL Loader class using particular AIR SDK discussed in #119 , so I started experimenting with different AIR SDKs. 

Currently, we were using AIR SDK 28.0. I tested with lower version, but that also thrown me same error. 

I downloaded the last AIR SDK 30.0 - this time I didn't had this error and able to land to the folder selection screen. So, this looks like SDK 30.0 is a requirement to the latest patch to SDK Installer codes.

I able to start the download, at the end of AIR SDK download (I was trying to download Apache Flex 4.16.1 with AIR 30.0), installer code thrown me this error - which is similar to what Alex mentioned at here - http://apache-flex-development.2333347.n4.nabble.com/Discuss-Apache-Flex-SDK-Installer-3-3-2-RC1-tp65400p65405.html:

```
Error: Error #1000: The system is out of memory.
	at flash.net::URLStream/readBytes()
	at flash.net::URLLoader/onComplete()
```

But why I told Alex's solution is complicated in implementation is because the solution is hacky, and non-intuitive - which is Alex also agreed to. 

I see what Alex's new solution was doing is (during my use to latest standalone Apache Flex SDK Installer):

- Starts the installer 
- Eventually you get an alert "This is the 32-bit Installer. It will close and launch the 64-bit Installer"
- Until it downloads the 64-bit installer at background you need to keep the application alive - or the said version will never complete download and you shall keep having that alert every time
- I received the download completion alert and it exit the application abruptly while I was in-mid of a download process 
- Therefore when it restart itself I able to complete my download
- Later, every time I opens the SDK Installer application from Start menu it opens, throws the 32-/64-bit alert, auto-close itself, and restarts with some 64-bit version 

Reading the solution in background at [here](This is the 32-bit Installer.  It will close and launch the 64-bit Installer) I see he produce two types of 32-bit installer, 64-bit captive runtime installer, therefore download and installs, modify Start menu options etc. - this is quite troublesome and not very friendly in a way. 

My question is, do we need to follow this hacky ways just to support Apache Flex SDK Installer to run through Moonshine? The solution Alex has at this moment, I don't want to proposed on Moonshine due to its complexity, non-intuitiveness. I understand Alex also don't have any other solution at this moment. 

Do we want to mess with our installer and installation stuff to support the newer in-build SDK installer?

**Comment by atinprominic** [comment]
It still throwing error. Please find attached document with details.

[Moonshine Apache Flex Dowload Error Log.docx](https://github.com/prominic/Moonshine-IDE/files/2201629/Moonshine.Apache.Flex.Dowload.Error.Log.docx)

**Comment by rat-moonshine** [comment]
> It still throwing error. Please find attached document with details.

Because I didn't commit any changes to the repository. The change is required to build with AIR SDK 30.0. We need to decide on whether we wants to port to 30.0 immediately or not, and then we shall need to setup latest SDK at Bamboo to build with.

**Comment by rat-moonshine** [comment]
I talk on this in length to Joel, although we couldn't able to reach to a productive decision because of the complexities involve to the latest patch approach suggested by Alex. 

If the existing SDK Installer code do not able to download newer SDKs and latest patch process is not approachable to Moonshine, then we might need to ask users to use standalone Apache installer to download SDKs.

**Comment by piotrzarzycki21** [comment]
This should work with 2.0.0
