### ISSUE TITLE
Code completion showing incorrect content inside Flex mx:Grid component

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#331]
When I'm showing code completion inside [mx:Grid](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/mx/containers/Grid.html) component it displays incorrect content. I should probably see at least GridItem or GridRow on the list.

![mxgrid](https://user-images.githubusercontent.com/24554795/43101560-fbbb3900-8ec8-11e8-8a43-4232dcf265e9.gif)

**Comment by joshtynjala** [comment]
Interesting... In other components, like `SkinnableContainer`, a component will define `[DefaultProperty]` metadata to indicate which property will be set by default when you add children in MXML. This is what the language server uses to determine what appears in the completion list.

Example: https://github.com/apache/flex-sdk/blob/3c3d2c01f26dbb15d6d15d83f295490bfa3c9a05/frameworks/projects/spark/src/spark/components/SkinnableContainer.as#L231

If `[DefaultProperty]` is missing, the language server includes only public properties and classes/components are omitted. It seems that the older MX components work a bit differently than the Spark components. I'll need some time to investigate this one because this seriously breaks my understanding of how MXML code completion is supposed to work.

**Comment by piotrzarzycki21** [comment]
@joshtynjala it looks like I just gave you a bit of a headache. :)

**Comment by piotrzarzycki21** [comment]
@joshtynjala I have tested it today and it seems to work now.
