### ISSUE TITLE
Visual Editor Project: Highlight code for the selected UI component

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#341]
While studying the generated XML of visual editor project, many times developer looks the corresponding code generated of the selected component. The developer should be provided with the highlighted code in the Code pane if he has selected any UI component in the Visual pane.

For example, developer has selected the component - "inputText" in the Visual Tab, then he moves to the Code tab. In this case the code of the corresponding component selected in the Visual tab should be highlighted.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have spent on this problem a lot of time and didn't find other solution than setting item null. 

You can try to dig into that, but I would rather remember somewhere selected index and reselect item again than tried to change current mechanism. Definitely I do not recommend holding somewhere item itself, cause I think after setting null there are a lot of things being clean up, so getting back the same item may not working as it was.

As for the place of VisualEditorView.mxml - At the time when I have created it it's fits for me in that place. Feel free to propose some other if you want.

**Comment by rat-moonshine** [comment]
Okay. Thank you for the insight @piotrzarzycki21 . I shall try to check if somewhat other way (than storing the selected item) is possible to hide/unhide the transformation pointers during change between 'Visual' and 'Code'. 

Regarding the `VisualEditorView.mxml` and two other events (in the same directory) location, I would rather suggest to move them into `ui.editor` section (where Visual Editor related file already present), under same project tree. `help` folder mainly planned for keeping application related information, tourDeFlex etc.

**Comment by piotrzarzycki21** [comment]
But VisualEditorView is something different than VisualEditorViewer. View is just UI representation of Visual Editor and Viewer is a real editor, so I'm not sure if View suits in ui.editor.

**Comment by rat-moonshine** [comment]
I need a way to determine which item is selected on stage, from the UI component itself. 

That means, I need to know if the self is selected from the `Button` component itself. At this moment, `EditingSurface.mxml` keeps a `selectedItem` property - but I don't see an UI component (i.e. Button, Div) has direct access to the `EditingSurface.mxml` file. I also didn't found any possible existing field which can tell me if the self is presently selected to the editor. 

The immediate solution I could able to think is to introduce a GET/SET method (i.e. `isSelected`) under certain interface class - so we can has the field available in both Flex and PrimeFaces components. 

@piotrzarzycki21 do you think this is a valid solution for this? Or you can suggest in which interface we can have that property added?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine my first thought was to create separate interfaces, but in the end we would like to have selectable in the code each new component. Go and add `isSelected` to `ISurfaceComponent`. The question is where do you see place where component can be marked as selected ?

**Comment by rat-moonshine** [comment]
Thank for this suggestion @piotrzarzycki21 . My thought is update a component's `isSelected` property from this [setter](https://github.com/prominic/MockupVisualEditor/blob/master/src/view/EditingSurface.mxml#L95) method.

**Comment by piotrzarzycki21** [comment]
It's fine with me. I believe if it won't be enough the second place for that may be in `BasePropertyEditor `class.

**Comment by rat-moonshine** [comment]
I chose to go with changes in `EditingSurface.mxml` @piotrzarzycki21 , we can move the codes to 2nd option if we see that is more relevant for some reason.

All the surface component class now affected/modified because of the new property addition to `ISurfaceComponent`, suggested to get an update from the Git. 

There are couple of questions I'm asking suggestion from everyone.

'Code' pane now open code-tag auto-selected based on current editor selection - user can remove the selection at this moment which opens few questions:

1. Do we want to not lost that selection if user clicks anywhere in the code?
2. If we want let the selection lost in a natural manner - when changing to 'Visual' shall the existing selected component remain show as selected?
3. If we do not want to lost the selection in 'Code' pane, then perhaps we want to use the existing not-losable selection we used in case of Projects > Search (in pink)
![image](https://user-images.githubusercontent.com/24370870/44026949-57555850-9f12-11e8-886d-a316479191e5.png)
Since the editor _xhtml_ file not includes in the `Project > Search` of Visual Editor Project, using this existing selection maybe worthy. But in future if we wants to include the _xhtml_ files also in `Project > Search`, then this selection may create conflict.

Let me know yours thoughts.

**Comment by piotrzarzycki21** [comment]
Here is my answers:
1. I believe it would be the best if we won't loose selection in code pane
2. If it will be a huge problem to do that, I'm fine with loosing selection
3. That's ok - do you have to do some large changes to use that mechanism ?

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just found that there is some issue with Visual Editor XML after your update in following scenario:
1) Have a clean project without any component on the surface.
2) Pickup Button, drop on surface and save changes
3) Go to visual editor XML and you will see following XML:

```
<mockup>
  <MainApplication title="" width="600" height="800" class="flexVerticalLayout flexVerticalLayoutLeft flexVerticalLayoutTop" wrap="false">
    <_moonshineSelected_Button width="100" height="30" disabled="false" value="Button" title="" isCommandButton="false" actionListener=""/>
  </MainApplication>
</mockup>
```

Please take a look into that!

**Comment by rat-moonshine** [comment]
I didn't had a chance to look into that part, but thanks for pointing to this, @piotrzarzycki21 . I shall look into this.

**Comment by JoelProminic** [comment]
@rat-moonshine, I don't have a strong opinion about your questions for highlighting vs selecting the code corresponding to the selected component.  Here are some thoughts:
- I think using highlighting rather than selection will probably look a little better.  Being able to click elsewhere in the code without clearing the highlighting would be nice for the uneditable code.   Use a light color if you chose this solution. 
- Using selection rather than highlighting would allow the code to be copied easily, but I don't think that is an important use case.

**Comment by rat-moonshine** [comment]
> <mockup>
>   <MainApplication title="" width="600" height="800" class="flexVerticalLayout flexVerticalLayoutLeft flexVerticalLayoutTop" wrap="false">
>     <_moonshineSelected_Button width="100" height="30" disabled="false" value="Button" title="" isCommandButton="false" actionListener=""/>
>   </MainApplication>
> </mockup>

Thankfully, the problem found exists only to the Button component, which is rectified now. I shall post updated SWC by EOD today.

**Comment by rat-moonshine** [comment]
This was something I wanted to do from long back - to tone-down that pink selection color. Actually, that color is taken from the Moonshine standard selection color at sidebar. 

As we all wants to keep the selection (to the tags) persists even after clicking anywhere in the code, I think it'd be best to re-use the same layer we used to highlight results in `Projects > Search`, rather than creating another new layer for the purpose. So, I moved to tone-down that pink color a bit, and I think the current output is more soothing than before, please check.

Highlight now persists even after clicking anywhere of the code. 

Transformation-tool pointers now hide/un between 'Code' and 'Visual' pane, as well.

**Comment by rat-moonshine** [comment]
Yes, I think this is more or less done, from my side.

@atinprominic you can test it now.

**Comment by atinprominic** [comment]
@rat-moonshine I have tested it and found that a couple of UI controls are not working as expected.

Please check the attached video recording.

![200818](https://user-images.githubusercontent.com/34882311/44330454-ae32c000-a484-11e8-9759-237d0fecb658.gif)

**Comment by rat-moonshine** [comment]
Hi @atinprominic , thank you for reporting this. 

I noticed missing of necessary codes in PanelGrid component which are requires for highlighting purpose; probably the component was in-work for other purpose at that time. This is now rectified. You should get a fix version build against PanelGrid by EOD today.

You may have noticed that some components' codes are not generated at all - during your tests. Thus, no highlighting happens against them. One which I know is `Include` and a discussion against this non-generation of code is already running at [here](https://github.com/prominic/Moonshine-IDE/issues/351). 

I also noticed codes not generated against `Tree` component that you dragged outside of the root Div tag. Since no code generated there were no highlight happens. On why code did not generated in that case - you probably want to report in a separate issue.

**Comment by atinprominic** [comment]
@rat-moonshine Ok. I will report for "the code not generated" issue separately if I will find this issue in future testing.

**Comment by atinprominic** [comment]
@rat-moonshine I tested and found that we should auto focus on the code highlighted. The user need to scroll down to check the highlighted code.See attached video.
![230818](https://user-images.githubusercontent.com/34882311/44506986-761abf80-a6c6-11e8-9bab-1d8d9197c412.gif)

**Comment by rat-moonshine** [comment]
I vaguely remember the auto-scroll handler was added; but I'm not certain anymore after seeing this. I agree, @atinprominic . We'll need this to have fixed.

**Comment by rat-moonshine** [comment]
@atinprominic , auto-scroll to selected tag should be fix in latest build now. With new changes, you shall have the selection with existing logic selection, but additional selection for tag-highlight (pink) will persists, too.

Please, check.

**Comment by atinprominic** [comment]
I tested and its working good.

**Comment by rat-moonshine** [comment]
Unfortunately, there was some trouble exists when previous tag selection highlights were not clearing effectively when component selection changed. 

This should be fixed by now.
