### ISSUE TITLE
Some options in project tree context menu for file creation are not disabled in Visual Editor projects

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#363]
In context menu of project tree in option **New** only **Visual Editor PrimeFaces file** and **Visual Editor Flex File** should be available accordingly to the type of project.

**Current state:**

![not_disabled](https://user-images.githubusercontent.com/24554795/45016262-67b49800-b024-11e8-9c28-fa51cc2a094b.png)

**Expected state:**

![expected_state](https://user-images.githubusercontent.com/24554795/45016328-916dbf00-b024-11e8-86ef-a800648f4659.png)

**Comment by rat-moonshine** [comment]
I think this was working 'expected' way before. I shall check what have been changed.

**Comment by piotrzarzycki21** [comment]
Yep. That screenshot is from 1.14.0. :)

**Comment by rat-moonshine** [comment]
Well, it looks like the problem is much widespread. 

1. `File > New` also shows all files options against Visual Editor projects
2. ActionScript project shows file types including MXML 

Part of the problem I think introduced since Git implementation - but I'm not sure how this overlooked from our tests for a long time.

Working on this now.

**Comment by rat-moonshine** [comment]
I made some modification to the structure on how files maps/enables against project menu types. Hopefully, the problem is being resolved now. 

By the new changes, Visual Editor project file now has these file options available:
![image](https://user-images.githubusercontent.com/24370870/45028658-8a19d600-b063-11e8-8d5f-3dbc84908f19.png)

The above file creation availability is based on my simple understanding; @piotrzarzycki21 voice if you think otherwise, I shall let the trouble options removed. 

I would also like you all to give some tests against these new changes, and see if any project-type<>available-options are not right. @atinprominic you can give some tests with this, too.

**Comment by piotrzarzycki21** [comment]
In Visual Editor type of project creating other type of file than VE doesn't make sense right now. If you provide such options, you need to as well handle that and open it using appropriate code syntax parser. I recommend go back to the previous state, unless we will have such requirements.

**Comment by rat-moonshine** [comment]
After the discussion with Joel, I kept 'File' type available only to the Visual Editor projects (if user wants to create any text file only for any note/documentation purpose). 

I also noticed that both types of (Flex and PrimeFaces) VE file creation available to a VE project - which is rectified now.

**Comment by piotrzarzycki21** [comment]
Ok, but does it work? I mean if you create such file and double click - what is happening ?

**Comment by rat-moonshine** [comment]
Creating a text file (File) opens the file in its usual manner to the editor - this do not renders as an visual editor stage. 

Creating Visual Editor Flex/PrimeFaces file opens as visual editor stage.

**Comment by atinprominic** [comment]
I tested it and found that the option to create the files is as per the project type.
