### ISSUE TITLE
Add PrimeFaces p:selectOneListbox component to Visual Editor

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#374]
More information about -> [p:selectOneListbox](https://www.primefaces.org/showcase/ui/input/listbox.xhtml)

**Comment by atinprominic** [comment]
Its working fine but I have below suggestions for improvement:

1. Instead of putting  in the last, move this UI Component to place with other Select components.
2. While selecting the values line item in properties box or in the UI control, the selected line item value should be in sync. Currently if I select the 2nd value in the UI control then the selected value in the properties box is not refocusing to the corresponding value line item.
