### ISSUE TITLE
Introduction of file Copy/Paste capability to project tree view

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#413]
The targeted feature to support following cases through context-menu options:

- Copy file from user's system to Moonshine opened project tree
- Copy/paste file from one location to another location within Moonshine opened project tree

This might need updating of language-server paths when a relevant file (i.e. ActionScript, MXML etc.) copied to Moonshine, but this a future thing.

**Comment by piotrzarzycki21** [comment]
Please if you start working on that, make branch features/issue_413_some meaningfull name.

**Comment by rat-moonshine** [comment]
Okay, sure thing.

**Comment by rat-moonshine** [comment]
Files and folders copying process to Moonshine project tree (from project tree or native system) now merged to the 'master' and ready for tests. During overwriting of files, Moonshine will also support overwriting in a fashioned manner:
![image](https://user-images.githubusercontent.com/24370870/48821897-1a250d00-ed81-11e8-8ea0-2635c6cd21c8.png)

This merge now decided to go with v1.16.0 due to late release.

**Comment by JoelProminic** [comment]
I did some tests on macOS:

Test | Source | Result
---- | ------ | ------
Copy a single file | System |  Works
Copy a single file | Moonshine | Works
Copy a single file (overwrite) | System | Works
Copy a single file (overwrite) | Moonshine | Works
Copy multiple files | System | Works
Copy multiple files | Moonshine | N/A - can't select multiple files
Copy multiple files (overwrite) | System | Works
Copy multiple files (overwrite) | Moonshine | N/A - can't select multiple files
Copy a directory | System | Works
Copy a directory | Moonshine | Works
Copy a directory (overwrite) | System | BUG: only prompts me to overwrite the directory itself
Copy a directory (overwrite) | Moonshine | BUG: only prompts me to overwrite the directory itself

Some tests for the overwrite prompt

Test | Single File | Multiple files 
---- | ----------- | -------------- 
Overwrite | Works | Works
Overwrite All | Works | Works
Skip File | Works | Works
Cancel All | Works | Works

When I try to overwrite a directory, I am prompted if I want to overwrite the directory itself, rather than the individual files.  I would expect this to instead iterate through the individual files in that I am pasting, and prompt me if I want to overwrite each one (if it already exists).

Otherwise, the code seems to work well for me.

**Comment by rat-moonshine** [comment]
> When I try to overwrite a directory, I am prompted if I want to overwrite the directory itself, rather than the individual files. I would expect this to instead iterate through the individual files in that I am pasting, and prompt me if I want to overwrite each one (if it already exists).

I admit the kind of handling mentioned above, I wanted to pass and took the simpler way. Doing the above process would take me look into every folder and their sub-folders, get the number of files through File API (some time this can be even slower just to get the list depending upon the content of a given folder), and therefore looping through each folder and sub-folders' contents to populate the alert notification against each item. 

If a folder have lots of files and sub-folders this may stress on the process. So I choose to notify against the root files/folders those were under the clipboard pointer. 

Let me know if we still want to have the above feature way.

**Comment by rat-moonshine** [comment]
Prompts to overwrite the directory and its individual contents added in a breadth-first policy.

**Comment by rat-moonshine** [comment]
Since macOS do not provides more logical handling in case of preventing parent from copying as its children (unlike Windows), handler added to prevent the copying process in Moonshine.

**Comment by rat-moonshine** [comment]
I'm closing this as initial target has completed. Raise separately if problem.
