### ISSUE TITLE
Basic Find Disabled for Java Projects

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#458]
When testing the Moonshine 1.16.0 on macOS and Windows, I noticed that Edit > Find is disabled for Java Maven projects.  Also, if projects of other types are open, then Edit > Find is disabled for them as well.

I can clear the problem by closing the Java project.

I haven't noticed this problem for other project types, but watch out for additional projects that may be affected when fixing this problem.

**Comment by rat-moonshine** [comment]
`Edit -> Find` feature is now available for Java projects as well.

For some project types (i.e. Visual Editor Project) this feature is not suppose to be active. However, the enable/disable of `Edit -> Find` is now works based on the selection in project sidebar. I can see this requires to be updated on tab-selection too to reduce confusion that Joel may had.

I shall work on above.

**Comment by JoelProminic** [comment]
Can you remind me why we disabled Edit > Find for Visual Editor Projects?   The default behavior doesn't make sense for the visual editor interface, but it would still be useful for:
- The Code tab (no replace)
- Other files in the project (i.e. pom.xml, .veditorproj, any Java JSF classes we add later)

If we need to keep the restriction for VisualEditor files, then I suggest that we restrict this by the currently editor/open focused, rather than the selected project.  For example, in the current behavior I see:
1. Open one Java project and one VisualEditor project
2. Open a Java file
3. Select a file in the Java project 
4. CMD-F - this works
5. Select a file in the Visual Editor project
6. CMD-F - BUG:  this does not work

**Comment by rat-moonshine** [comment]
The reason to keep the top menu options' state (enable/disable) change based on project sidebar selection was - from beginning to compile project between multiple opened projects, we choose to go by the current selection in the project tree. Thus, based on that project sidebar selection, top menu options for different project types' compilation enable or disable appropriately, this valid for other top menu options as well.

If we want to move that logic of menu state changes to current editor selection instead, then we might require to remove that logic completely from project sidebar selection. Because having this logic in two places will create confusion, example:
- Project sidebar has Flex project selected (which should enable Project -> Build Project)
- Selected editor is Away Builder (which shouldn't enable Project -> Build Project)

In case of Visual Editor Project, to Moonshine it'd take an extra effort to determine if visual editor interface is visible or the text editor (as it doesn't make sense Find to open in visual editor section). During that time, we choose to disable the option for time.

**Comment by piotrzarzycki21** [comment]
I like how it currently work, even if it sometimes cumbersome a bit cause you need to have selected something in side bar. However in case of Visual Editor find - why bother about selected tab Visual/Code? If I have opened visual editor view and hit `Edit` -> `Find` - let's search and in a moment of hit Find button we could switch in this specific view to tab Code.
Of course title of that window should be changed and we should hid Replace buttons. 

How about that idea ?

**Comment by JoelProminic** [comment]
I think @piotrzarzycki21's idea makes sense.  

Didn't we have a feature where the code for the currently selected component would be highlighted in the Code tab, and vice-versa?  When I tried that today, it did not work.   If this was working, we could search for a component like this:
1. Open Visual Editor
2. CMD/CTRL-F
3. Type the name of the component or label
4. The interface automatically switches to the Code tab
5. Switch back to the Visual Tab.  The corresponding component is highlighted.

This probably isn't the ideal user experience, but this is a feature I could see myself using when working on larger database conversion.

If I am misremembering the code higlighting logic, then the simple search in the Code tab is still the most logical action for the Visual Editor.

**Comment by rat-moonshine** [comment]
> Didn't we have a feature where the code for the currently selected component would be highlighted in the Code tab, and vice-versa?

This was suppose to work one-way - to highlight appropriate code in Code tab based on component selection in visual editor. I see this is not working anymore in latest source. I am not aware when this stopped working.

**Comment by piotrzarzycki21** [comment]
> > Didn't we have a feature where the code for the currently selected component would be highlighted in the Code tab, and vice-versa?
> 
> This was suppose to work one-way - to highlight appropriate code in Code tab based on component selection in visual editor. I see this is not working anymore in latest source. I am not aware when this stopped working.

Will you check and raise separate issue for that in future ?

**Comment by rat-moonshine** [comment]
I didn't have chance to think more on this, since the suggested purpose behavior same as this issue, let this issue be open for easy referencing and further enhancements.

**Comment by piotrzarzycki21** [comment]
I have raised two separate issues to cover disussion #510 and #511 - If something need to be done more raise new issue.
