### ISSUE TITLE
Build Java Gradle Applications

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#519]
Sorry, I missed your earlier question.  Unless we can find a reliable way to read the executable path, I think that we can hide Build & Run for Java Gradle projects.

For Project > Build, I think we should just run "$GRADLE_HOME/bin/gradle clean build" by default.  You can see all of the other tasks that will be executed with this command:

    $ gradle clean build
    Starting a Gradle Daemon (subsequent builds will be faster)
    :clean UP-TO-DATE
    :compileJava
    :processResources NO-SOURCE
    :classes
    :jar
    :assemble
    :compileTestJava NO-SOURCE
    :processTestResources NO-SOURCE
    :testClasses UP-TO-DATE
    :test NO-SOURCE
    :check UP-TO-DATE
    :build

A more advanced solution would be to let the user configure the tasks for Gradle, similar to the Build actions for Maven.

Is there some limitation I am forgetting that prevents us from running Gradle builds like this?

_Originally posted by @JoelProminic in https://github.com/prominic/Moonshine-IDE/issues/459#issuecomment-482613819_

**Comment by piotrzarzycki21** [comment]
Additional reference comment https://github.com/prominic/Moonshine-IDE/issues/459#issuecomment-482716654

**Comment by JoelProminic** [comment]
Note that currently (pre-2.1.0) we do not have a way to configure a Gradle installation in Moonshine, and it is not installed with Moonshine SDK Installer.  We'll at least need a settings page for this if we want to include this issue in 2.2.0.

Gradle provides a wrapper that will automatically install the correct Gradle version for a project:  https://docs.gradle.org/current/userguide/gradle_wrapper.html
However, this may require access to the home directory in order to save the downloaded copy of Gradle, which could trigger errors with the macOS sandbox.

**Comment by JoelProminic** [comment]
I added this to the 2.3.0 milestone.  For this release, don't worry about a "Build & Run", just an action to run Gradle with a configured list of tasks.  Note that the user can add support to run the application from Gradle with the ["application" plugin](https://docs.gradle.org/current/userguide/application_plugin.html) - we could consider adding this to the default Java Gradle project.

Note that we had some trouble with Gradle projects in #547.  If we can't resolve this soon, we may push Java Gradle support to a later release.

**Comment by JoelProminic** [comment]
I found that we need to run a Gradle command to regenerate the classpath for the language server.  I have a proposed solutions for this here:  https://github.com/prominic/Moonshine-IDE/issues/547#issuecomment-491093384

**Comment by JoelProminic** [comment]
@rat-moonshine started adding Gradle to Moonshine SDK Installer here:  https://github.com/prominic/Moonshine-SDK-Installer/issues/9

**Comment by JoelProminic** [comment]
@rat-moonshine added a Gradle Build > Build Actions setting (https://github.com/prominic/Moonshine-IDE/issues/547#issuecomment-492595298).  However, I found that the setting was reset when I restarted Moonshine.  Please change this to "Build Tasks" for to match the Gradle terminology.

@rat-moonshine also added these Project menu actions:
- Build - this will run <gradle-home>/bin/gradle <build-actions>
- Build & Run - this will run the same action as Build, and then also run <gradle-home/bin/gradle run
- Clean - I need to clarify this logic

I have some concerns about this implementation:
- Build & Run will fail if the application plugin is not configured in build.gradle
- I could set the build task to "clean", and Project > Build would no longer be building anything
- I could set the build task to "run", and then Build & Run would execute the application twice.

I would like to replace Build and Build & Run with an action called "Run Gradle Tasks".  This will run the configured tasks from the settings.  We can keep Clean for now, since this will always be available for a Gradle project.

In order to have a "running" example for new Java Gradle projects, build.gradle should be configured with "run" as the default task, and have the application plugin and main class set by default.

**Comment by rat-moonshine** [comment]
- Gradle project menu now have "Run Gradle Tasks" instead of "Build" and "Build & Run" option (the option generally does `gradle <buildTask>` and close the process)
- Default build action to Gradle project template is now "clean run" (I'm not sure if Joel ask specifically for "run" instead of "clean run" - but we have only "clean run" in present build action list)

Regarding `Project > Clean` option, I want to mention that the option do not run any Gradle action; But it clears one or many physical folders. In case of Gradle it clears 'build' folder, in case of Maven project it clears 'target' folder (as in case of Flex projects it generally clears 'bin-debug' and maybe other few items).

A few bug I noticed during my tests, which have rectified now; They are as follows:
1. `<option mainclass="$ProjectName"/>` is populating to .javaproj after a settings' save for Gradle projects
2. Following tags found missing to .javaproj file after a settings' save for Maven or Gradle projects - which are part of the original configuration/template:
```
<classpaths>
    <class path="src/main/java"/>
</classpaths>
```

**Comment by JoelProminic** [comment]
I verified that the additional bugs you reported have been fixed.   Project > Clean is now using "gradle clean".  I am closing this issue.
