### ISSUE TITLE
Maven Build Path Prevents Actionscript Build

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#521]
I noticed this behavior today:
1. Checkout an Actionscript project from SVN
2. Project > Build & Run
3. Moonshine reported an error about the Maven path

    : Following path(s) are invalid or does not exists:
    : Maven Build Path: C:\Users\<another-user>\Desktop\DataCenterVisualizer_2018

Maven Build Path was set to the absolute build path of the project from another user's workstation.  This setting was preserved in SVN, so it was set incorrectly for my workstation.

You can also trigger the error like this:
1. Create a new Actionscript AIR project
2. Create a directory in the new project called mavenbuild
3. In the project settings, set Maven Build Path to mavenbuild
4. Rename mavenbuild to mavenbuild2
5. Project > Build & Run.  BUG:   Moonshine reports an error like this:

    : Following path(s) are invalid or does not exists:
    : Maven Build Path: <path-to-project>/TestMavenBuildPath_Actionscript/mavenbuild

Note that Actionscript projects do not use Apache Maven, so this error should not happen for this project type (or other project types besides Java Maven or Visual Editor PrimeFaces).)

We should also consider whether the Maven Build Path should be defined as an absolute path by default, since this will cause trouble when using Git or SVN.

I think I remember seeing an error similar to this before, but I couldn't find an issue for it.

**Comment by piotrzarzycki21** [comment]
> * Rename mavenbuild to mavenbuild2
> * Project > Build & Run.  BUG:   Moonshine reports an error like this:
>   : Following path(s) are invalid or does not exists:
>   : Maven Build Path: /TestMavenBuildPath_Actionscript/mavenbuild

I'm not following where the problem is here. Are you suggesting that renaming should update path to Maven build folder ?

**Comment by piotrzarzycki21** [comment]
> Note that Actionscript projects do not use Apache Maven, so this error should not happen for this project type (or other project types besides Java Maven or Visual Editor PrimeFaces).)

If we are talking about pure ActionScript project maybe not, but in case of Flex Desktop/Web project those can use Maven, so option should remains for that.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I think there is some issue in your implementation. You are checking before the build whether [maven path exists](https://github.com/prominic/Moonshine-IDE/blob/e632c5222279ee972ae26e6921ff80ed0fc27f0c/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/build/CompilerPluginBase.as#L88). In my opinion it shouldn't happen for any of project. Joel's scenario illustrate that is failed when someone would like to build project which doesn't contains Maven build. 

That's just one sight, the second is that we should leave for the Maven itself check whether path is ok or not. Build should just start with provided path without our intervention. That said code [pom check](https://github.com/prominic/Moonshine-IDE/blob/e632c5222279ee972ae26e6921ff80ed0fc27f0c/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/build/CompilerPluginBase.as#L88), [settings check](https://github.com/prominic/Moonshine-IDE/blob/e632c5222279ee972ae26e6921ff80ed0fc27f0c/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/build/CompilerPluginBase.as#L93) and [pom check for Java project](https://github.com/prominic/Moonshine-IDE/blob/e632c5222279ee972ae26e6921ff80ed0fc27f0c/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/build/CompilerPluginBase.as#L115) should be removed.

**Comment by rat-moonshine** [comment]
[That](https://github.com/prominic/Moonshine-IDE/blob/e632c5222279ee972ae26e6921ff80ed0fc27f0c/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/build/CompilerPluginBase.as#L88) is a standard path existence check against all the path-fields available to a project VO. This has a certain conditional test if the path-field is _non-null_. 

If we do not want Maven build against certain _types_ of projects, then we shouldn't populate the "Maven Build" path to the project's settings. This will help to reduce confusion and keep the settings clean by not including an unnecessary field/section. I guess this will also keep the path-field _null_ to not to get into the path-existence check.

If we can not populate a valid Maven path at this moment, then it shouldn't auto-populate a non-Maven path as it is doing now.

**Comment by piotrzarzycki21** [comment]
> If we do not want Maven build against certain _types_ of projects, then we shouldn't populate the "Maven Build" path to the project's settings. This will help to reduce confusion and keep the settings clean by not including an unnecessary field/section.

No this is not the case here. Project can be compiled by Maven and internal compiler ex. Royale, Flex projects.

**Comment by piotrzarzycki21** [comment]
> If we can not populate a valid Maven path at this moment, then it shouldn't auto-populate a non-Maven path as it is doing now. This will keep the associated path-field _null_ as well. (should support Joe's case)

This is workaround which I don't like. You are doing checking for that path in order to display some message. Let Maven build handle such stuff instead we are doing that. You are avoid real error by having that checks.

**Comment by piotrzarzycki21** [comment]
Another thing is that you [have check](https://github.com/prominic/Moonshine-IDE/blob/e632c5222279ee972ae26e6921ff80ed0fc27f0c/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/build/CompilerPluginBase.as#L93) whether whether Maven settings file exists - this is definitely wrong, cause Maven has default settings file which is loaded if our provided doesn't exists.

**Comment by piotrzarzycki21** [comment]
This is what you are getting from Maven when path is wrong:

`: [ERROR] The goal you specified requires a project to execute but there is no POM in this directory (D:\Work\projects\Prominic.NET\MoonshineTests\NewJavaMavenProject\maven). Please verify you invoked Maven from the correct directory. -> [Help 1]`

**Comment by piotrzarzycki21** [comment]
I'm getting following errors when Moonshine is starting:
![errors](https://user-images.githubusercontent.com/24554795/56288047-32296e80-611e-11e9-88ee-c140cd2a3a1e.png)

This is probably due to [that](https://github.com/prominic/Moonshine-IDE/blob/8bad74e0959bf1550531d412648fe9c61cc9ddc3/ide/MoonshineDESKTOPevolved/src/actionScripts/impls/IFileBridgeImp.as#L594) code. It should be reported to the console or should be handled for specific UI in some layer when it happen. 
If I would have workspace with 50 project I would get 50 popups.

**Comment by rat-moonshine** [comment]
> This is workaround which I don't like. You are doing checking for that path in order to display some message.

I don't know what is wrong to ask to not to auto-populate an invalid path to "Maven Build File". If you are not sure about the path you're auto-populating, just do not auto-populate. Currently, it is populating a folder path to the "Maven Build File" which is wrong:

![image](https://user-images.githubusercontent.com/24370870/56288452-762b6c00-613c-11e9-8273-d0b5f8b64583.png)

Prior to build, Moonshine is doing a parity check, to ensure all the dependency paths are exists; There should be nothing wrong to that. If any path is wrong, or does not exists, it report to the console, so an user can fix the problem before compilation breaks. Generally, this auto-populated "Maven Build File" path do not report any error (even when the path is logically wrong) as it pointed to the project root. The problem came to action when a case like Joel's happens. 

> Let Maven build handle such stuff instead we are doing that. You are avoid real error by having that checks.

I really shouldn't worry about what Maven build will report, I only checks whether all the associated and dependency paths are valid prior to a project compilation. If you think prior to a project compilation, we do not need path-existence check to "Maven Build File", then I will remove it. 

> Another thing is that you have check whether whether Maven settings file exists - this is definitely wrong, cause Maven has default settings file which is loaded if our provided doesn't exists.

That is fine, I can remove that check then. I really do not know much about how Maven plugin collects and stores its information.

> This is probably due to that code. It should be reported to the console or should be handled for specific UI in some layer when it happen.
> If I would have workspace with 50 project I would get 50 popups.

I see your point. For some reason (probably) I choose to put an alert, but probably it's best to have them populated in console only.

**Comment by piotrzarzycki21** [comment]
I will raise separate issue if needed for work on Maven path.
