### ISSUE TITLE
Java Projects Do Not Fully Delete

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#526]
When I delete a Java Maven project, I am left with these files on the filesystem:
- target/
- <project>.javaproj

I expect this to behave the same way for Java Gradle projects.

**Comment by rat-moonshine** [comment]
I see some files are not showing for Java Gradle project to sidebar when they are exists in file-system:

(files as displayed in Windows Explorer)
![image](https://user-images.githubusercontent.com/24370870/56341209-ec2de280-61d1-11e9-9f4c-8b788c33033c.png)

(files as displayed in sidebar to the project)
![image](https://user-images.githubusercontent.com/24370870/56341232-fea81c00-61d1-11e9-8f50-c0ecf853f694.png)

The latter probably because of ways in hidden file handling to Moonshine. [Here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/components/popup/ProjectDeletionPopup.mxml#L118) is a check for hidden files to the project to include in the project deletion process, however I found the field is empty or an empty array. @piotrzarzycki21 do you have any details when this `hiddenPaths` field is suppose to be populated, whether the field is suppose to be populated with the items those we are not seeing in the sidebar?

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 do you have any details when this `hiddenPaths` field is suppose to be populated, whether the field is suppose to be populated with the items those we are not seeing in the sidebar?

Exactly those are paths which won't be visible in sidebars. We are using it in VisualEditor type of projects.

**Comment by rat-moonshine** [comment]
> 
> 
> > @piotrzarzycki21 do you have any details when this `hiddenPaths` field is suppose to be populated, whether the field is suppose to be populated with the items those we are not seeing in the sidebar?
> 
> Exactly those are paths which won't be visible in sidebars. We are using it in VisualEditor type of projects.

That says why `hiddenPaths` field is not populating in case of Java project. But I'm wondering how sidebar decides not to populate some files/folders in case of Java project. I see those files/folders generates at the time of Java project creation.

**Comment by piotrzarzycki21** [comment]
> That says why `hiddenPaths` field is not populating in case of Java project. But I'm wondering how sidebar decides not to populate some files/folders in case of Java project. I see those files/folders generates at the time of Java project creation.

Maybe it is in default project creation template ?

**Comment by rat-moonshine** [comment]
Okay, this is something interesting. 

1. Create a new Java Gradle project
2. Project populates to the sidebar without files/folders those starts with dot
3. Can do multiple 'Refresh' to the project root - doesn't make any difference to the project tree
4. Right-click on project root and choose 'Delete' 
5. Next just cancel the opened 'Delete Project' dialog
6. Re-do 'Refresh' to the project root in sidebar
7. Now you can see all the files/folders start with dot appears to the tree! [BUG?]

**Comment by rat-moonshine** [comment]
I have updated the file list to be include in delete process during Java project deletion. This is to note, that some files generates after the project been created, I think they generates after the language server start completely. These files not supplied by the project template, files and folders starts with dot. 

User needs to wait until the server starts completely (bottom-left notification) and Moonshine completes its process to generate those files. Once that done, Moonshine can list them all in the project deletion dialog and delete them when requested. 

If the deletion dialog opens before that, then there is a chance to miss some files not being listed (because they not yet generated) and eventually left them from deleting.

**Comment by JoelProminic** [comment]
I confirmed that deletion works now.  I tested on both Maven and Build projects, and ran a simple build for both projects before deletion to populate the projects with files expected during normal usage.
