### ISSUE TITLE
Move "References" window to console area

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#553]
I have found very inconvenient to use References window when it is showing as popup. Let's move it to console area where it will be much more useful.

**Comment by JoelProminic** [comment]
I assume you are talking about the View > Find References action.  When I try this action (with the macOS AppStore build) with a symbol selected, Moonshine opens a tab like this:
![image](https://user-images.githubusercontent.com/24532731/58134272-e28e0500-7beb-11e9-92bb-bd7e7d6e3564.png)

Some notes:
- The References tab is not closable, unlike the Problems interface.  I feel this should be closable, but this is a distraction rather than something that interferes with my work.
- If you previously opened the References tab and then switched to the Console, the Reference tab will not get focus or report activity if you search for another reference.
- The list in the UI looks strange - there are black gaps between the rows.
- If I try View > Find References and there are no matches, the References window does not open, and there are no reported errors.   View > Document Symbols and Workspace Symbols have a similar issue - we may want to revisit this in a separate issue.

**Comment by piotrzarzycki21** [comment]
> * The References tab is not closable, unlike the Problems interface.  I feel this should be closable, but this is a distraction rather than something that interferes with my work.

I have fixed this issue.

**Comment by piotrzarzycki21** [comment]
> * The list in the UI looks strange - there are black gaps between the rows.

I made smaller gaps and align list style with ProblemsView

**Comment by piotrzarzycki21** [comment]
I have raised new issue for the rest improvements.
