### ISSUE TITLE
Custom SDK Does Not Work for New Projects

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#566]
I noticed this error today as we were doing final testing for the 2.3.0 release:
1. Set the default SDK to a Royale SDK
1. Create a new ActionScript AIR project (also confirmed with Flex Desktop).  Note that the Custom SDK is set to a Flex SDK, and it does not show any errors
1. Try to build the project.  Moonshine reports ": Invalid SDK - Please configure a Flex SDK instead. "
1. Open the project settings, and check the custom SDK.  This shows an error that the SDK is invalid, but the label looks correct
1. Open the .as3proj file.  The SDK is set like this: ```<option customSDK="Apache Flex 4.16.1 FP32.0 AIR32.0 en_US"/>```
1. Manually change the custom SDK to the same Flex SDK.   
1. Open the .as3proj file.  The SDK is set like this: ```<option customSDK="/Users/-user-/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0"/>```

I see the Moonshine is setting the custom SDK as a label in project creation, but it expects an absolute path. 

We need to correct this so that new SDKs are configured properly so that they can run without further customization.

(Side Note:  Using the absolute path is problematic because it won't work when the project is shared with SVN or Git.   However, if Moonshine was supposed to use the absolute path, don't worry about changing this logic now - we could save this as a future improvement.)

**Comment by piotrzarzycki21** [comment]
After your fix try scenario where you have Java sources (no ide moonshine file) and you are importing it.

**Comment by rat-moonshine** [comment]
This looks like due to recent many a changes to the CreateProject class made some side-effect in functionalities here and there. Let's try not to call [setAutoSuggestSDKbyType()](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/CreateProject.as#L1072) in multiple places. 

I gave more tests in regular project creation and import/project-creation logic in both Windows and macOS. These test-cases also involved recent break that I/Joel reported to #559 ([strange-cases](https://github.com/prominic/Moonshine-IDE/issues/559#issuecomment-496869783)).

Following are my test-cases in general:

Project Creation Type | Description | Result
------------------ | ---------------------------------------------------- | --------------------
Regular | Suggested/Custom SDK auto-selected | Project creates properly with correct custom-sdk definition
Regular | Changed suggested/custom SDK in SDK dropdown | Project creates properly with correct custom-sdk definition
Regular | Java project creation | Custom SDK is not applicable
Import | Pre-suggested or changed SDK in SDK dropdown | Project creates properly with correct custom-sdk definition
Import | Java project import and changing the template type to 'Java' now disables the SDK dropdown | Project creates properly with correct custom-sdk definition

@piotrzarzycki21 give some tests and let me know if you see any breaks here or there.

**Comment by piotrzarzycki21** [comment]
I just give a quick test and it doesn't seems to be anything wrong right now.

**Comment by rat-moonshine** [comment]
> 
> 
> I just give a quick test and it doesn't seems to be anything wrong right now.

What does that mean?

**Comment by JoelProminic** [comment]
I don't see any remaining problems with this.  I tested with a variety of project types on each of the builds (Windows, App Store, macOS non-sandbox).
