### ISSUE TITLE
Java Gradle:  "Build class contains duplicate entry"

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#645]
I've been getting "Build class contains duplicate entry" errors for Gradle projects (since 2.4.0, at least).  I normally see it on projects that were converted from Eclipse, but I can reproduce it like this (macOS 10.10.5, Moonshine 2.5.0):
1. Create a new Java Gradle project
1. Language server starts with no errors
1. Project > Clean
1. Project > Refresh Gradle Classpath
1. I get this error on the console:

    : Project cleaned succssfully.
    : :eclipseClasspath
    : :eclipseJdt
    : :eclipseProject
    : :eclipse
    : BUILD SUCCESSFUL
    : Total time: 0.898 secs
    : Dec 20, 2019 3:31:22 PM Error occured while building workspace. Details: 
    :  message: Build path contains duplicate entry: 'src/main/java' for project 'TestGradleDuplicateEntry'; code: 977; resource: /Users/-censored-/Documents/Flex/temp_workspace/TestGradleDuplicateEntry;
    :  message: The project cannot be built until build path errors are resolved; code: 0; resource: /Users/-censored-/Documents/Flex/temp_workspace/TestGradleDuplicateEntry;

The language server seems to still work, though, so this seems to be mostly just a distraction.  This is not a high priority.

I don't see an obvious problem with the gradle configuration:

```
plugins {
    id 'java'
    id 'application'  // allows 'run' task.
    id 'eclipse'      // allows dependencies to be exported to .classpath
}
mainClassName = 'TestGradleDuplicateEntry'
repositories {
    mavenCentral()
}
sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
    }
}
```

**Comment by joshtynjala** [comment]
I am not able to reproduce this issue.

My output:

```
: Project cleaned successfully.
: > Task :eclipseClasspath
: > Task :eclipseJdt
: > Task :eclipseProject
: > Task :eclipse
: 
: BUILD SUCCESSFUL in 1s
: 3 actionable tasks: 3 executed
```

Windows 10

**Comment by joshtynjala** [comment]
Can you share the contents of _.classpath_ before and after the error occurs? You may need to "refresh" the file tree to see it after it gets created.

**Comment by JoelProminic** [comment]
I have been seeing this error regularly on macOS 10.10.5.

Here is the initial classpath:

    <?xml version="1.0" encoding="UTF-8"?>
    <classpath>
            <classpathentry kind="src" output="bin/main" path="src/main/java">
                    <attributes>
                            <attribute name="gradle_scope" value="main"/>
                            <attribute name="gradle_used_by_scope" value="main,test"/>
                    </attributes>
            </classpathentry>
            <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
            <classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
            <classpathentry kind="output" path="bin/default"/>
    </classpath>


And after cleaning the project and refreshing the classpath:

    <?xml version="1.0" encoding="UTF-8"?>
    <classpath>
            <classpathentry output="bin/main" kind="src" path="src/main/java">
                    <attributes>
                            <attribute name="gradle_scope" value="main"/>
                            <attribute name="gradle_used_by_scope" value="main,test"/>
                    </attributes>
            </classpathentry>
            <classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
            <classpathentry path="bin/default" kind="output"/>
            <classpathentry path="bin" kind="output"/>
            <classpathentry kind="src" path="src/main/java"/>
            <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
    </classpath>



The formats are slightly different, so it looks like these two files have been generated by different code.  Cleaning up the format a little, I can see that these two entries are added:

            <classpathentry kind="output" path="bin"/>
            <classpathentry kind="src" path="src/main/java"/>


If I remove .classpath and run `gradle eclipse` from a Terminal, I get a different output.  This has the additional entries from above:

    <?xml version="1.0" encoding="UTF-8"?>
    <classpath>
            <classpathentry path="bin" kind="output"/>
            <classpathentry kind="src" path="src/main/java"/>
            <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
    </classpath>

**Comment by joshtynjala** [comment]
I think that this is a conflict with the Java language server. The language server automatically creates a _.classpath_ file (and various other Eclipse project files), so maybe there's some kind of race condition or something.

I warned about this conflict before. I don't think that our Moonshine should be running the **gradle eclipse** command for Java projects at all. The language server should be the only thing that modifies the Eclipse project files. (It's fine in Groovy/Grails projects because that language server doesn't know anything about Gradle).

I recommend removing any option to run the **gradle eclipse** command in Moonshine Java projects. Unfortunately, someone else added this code to Moonshine, so I don't know the exact issue that it was meant to fix. It seems that we need to re-discover that reason (unless someone can point to the related bug report) and find a different fix for it that's more stable.

**Comment by JoelProminic** [comment]
We added the "gradle eclipse" logic because otherwise the language server was not supporting external dependencies.  The original problem is described here:  https://github.com/prominic/Moonshine-IDE/issues/547#issuecomment-490290118

Unfortunately I can not easily retest this now, because Moonshine is running "gradle eclipse" automatically before it starts the language server.

Now that I am thinking about this further, I remember we had an issue with the language server using an older Gradle dependency:  #552.  This might explain some of the format discrepancies in .classpath.

**Comment by joshtynjala** [comment]
Thanks for that. I looked at your sample projects in https://github.com/prominic/Moonshine-IDE/issues/547#issuecomment-490290118, and it looks like the dependencies resolve correctly when I open them VSCode, which shouldn't be using **gradle eclipse** at all. With that in mind, we know that it should be possible to do the same in Moonshine because it is the same language server in both. I'll investigate further to see if I can figure out why Moonshine isn't finding those dependencies.

**Comment by joshtynjala** [comment]
I tried removing the **gradle eclipse** command before launching the Java language server. Even without it, I can see that all dependencies are getting picked up correctly when you open a Java project in Moonshine. However, if you modify _build.gradle_ while the project is open inside Moonshine, this change is not detected by the language server, so it gets out of sync. I suspect that this behavior may be what made it seem like dependencies were being ignored. As it stands, if you close and re-open the project after you modify _build.gradle_, its new content is properly detected.

This is because our language server implementation currently does not support one particular notification that the Java language server is using to detect if _build.gradle_ has been modified. I've been avoiding implementing this notification because Adobe AIR's file system APIs are limited compared to Node.js or Java, and I will probably have to launch a separate native process to make it work. It seems like I've avoided that work long enough, and it's time to fix this limitation once and for all.

**Comment by JoelProminic** [comment]
I tested adding different dependency types to build.gradle, and confirmed that the language server automatically updated with the new available classes.   I'll report any cases I find where a dependency is not automatically recognized.
