### ISSUE TITLE
Build and Debug: Doesn't work if Node.js Home is set to /usr/local/bin

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#708]
I installed Node.js using the macOS installer from nodejs.org. This creates the `/usr/local/bin/node` executable.

If I set **Node.js Home** in Moonshine's settings to `/usr/local/bin`, I get the following error when trying to Build & Debug.

> A valid Node.js path must be defined to start an HTTP server for Project "ProjectName"

This worked correctly before, and it is now broken.

**Comment by rat-moonshine** [comment]
So far the standard path setup for other SDKs in Moonshine used to be pointing to the root directory, i.e. `/Downloads/MoonshineSDKs/Gradle/gradle-5.4.1-bin` etc.

Moonshine SDK Installer when installs Node.js from nodejs.org this setup in Moonshine by the following directory (based on the usual unzip process):
`/Downloads/MoonshineSDKs/NodeJS/node-v12.16.1-darwin-x64`

I remember we noticed problem accessing Node.js from different sections therefore, @JoelProminic can remember this more clearly...

As I understand the problems around calling node/exe in Moonshine now is:

1. When setup-path is `/Downloads/MoonshineSDKs/NodeJS/node-v12.16.1-darwin-x64` and node-js module trying to call appending `/bin/node` - it success
2. When setup-path is `/usr/local/bin` and Moonshine appends `bin/node` - it fails

Perhaps, an additional `bin` check may overcome this problem in corresponding sections, although not a very clean solution.

**Comment by joshtynjala** [comment]
Yeah, I saw that you download a zip (or maybe tar.gz) file. I used the installer, which doesn't seem to place Node in its own dedicated folder. On my system, there is no such thing as a "Node.js Home" folder.

Perhaps we should ask for the path to the executable instead of a folder.

**Comment by JoelProminic** [comment]
I think we couldn't select the binary directly previously.  I see it is not selectable now, but this may just be because of the settings of the FileChooser:
![image](https://user-images.githubusercontent.com/24532731/85450533-7acc8b00-b55e-11ea-9661-198dfbd93a1c.png)

We should be validating that `node` exists at the expected location for the selected SDK path.   I'm fine with the expected path being either `bin/node` or `node` (or both, if we want to make the logic a little more complicated), so long as we have some logic to validate that the path is valid.  I think we have similar logic for the other SDKs already.

**Comment by rat-moonshine** [comment]
Due to the difference in installation folders in macOS, I have updated the node-executable detection [logic](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/utils/UtilsCore.as#L1267) that should fix the problem. 

SDK folder setup remains directory specific. Please, check.

**Comment by joshtynjala** [comment]
Looks good! Thanks.
