### ISSUE TITLE
Code-completion 'index out of bounds' and other problem

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#71]
I tested this opening an ActionScript project. 

**How to reproduce**
- Declare an _Object_ type of variable
- After the variable pressing _dot_ syntax opens up the code-completion list
![image](https://user-images.githubusercontent.com/24370870/33003420-9afa259e-cde0-11e7-93ca-0962dc1bde7d.png)
- Pressing the "i" filters the list to "isPrototypeOf" item only
- [BUG] Pressing backspace do not restores the code-completion list
- Press backspace button again to remove the _dot_ syntax
- Press the _dot_ syntax again and try to re-do the steps from beginning
- [BUG] At a time while re-doing the above steps continuously, Moonshine throws an 'index out of bounds' error
![image](https://user-images.githubusercontent.com/24370870/33003483-05a23bca-cde1-11e7-9341-2d8f273e9f46.png)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I have seen this one. I didn't raise issue cause I couldn't reproduce it in installed version, but maybe this issue is swallowed in some way.

**Comment by rat-moonshine** [comment]
I able to produce the item filtering problem in my Windows 1.6.1 installation, though. The error - that probably avail only in debug version run.

**Comment by joshtynjala** [comment]
> [BUG] Pressing backspace do not restores the code-completion list

In commit d5969750fcfed3dd48eca1bcaa4c37c28741f643, the original source Array used by the data provider is modified with filter() [here](https://github.com/prominic/Moonshine-IDE/commit/d5969750fcfed3dd48eca1bcaa4c37c28741f643#diff-d295e45fbdeabd29909dbfc75f73db32R148), and the items are lost. I have modified it to use an ArrayCollection with filterFunction instead so that the data provider is filtered without losing items.

> [BUG] At a time while re-doing the above steps continuously, Moonshine throws an 'index out of bounds' error

I cannot reproduce this issue.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I can reproduce "index ouf of bounds" error every time. It occurs on several scenarios but I have tried to extract some scenarios. Here is one with gif recorded. It's all about playing with Enter, Backspace, Tab and `<`
**Scenario:**
1) Set cursor at the end of `<js:initialView>`
2) Hit Enter, Backspace and Tab
3) Type `<`, Backspace to delete typed sign
4) Hit Enter, Backspace and Tab
5) Type `<`, Back to "1" using Backspace

Repeat above scenario couple of times and you should reproduce that problem. Once you reproduce it once, it occurs more often. As you can see on the gif I did "Continue" and later reproduce it on the first attempt with above scenario.

![index_ouf_of_bounds](https://user-images.githubusercontent.com/24554795/33312959-a0fee0c0-d429-11e7-98fc-ba2009f7c788.gif)
[RoyaleTestProject.zip](https://github.com/prominic/Moonshine-IDE/files/1509281/RoyaleTestProject.zip)

**Comment by joshtynjala** [comment]
@piotrzarzycki21 @rat-moonshine Even with the new instructions, I still cannot reproduce the "index out of bounds error".

This error isn't happen inside the language server, so it seems like a bug that you don't necessarily need me to work on. Especially since you guys seem to be able to reproduce it so easily and I cannot. I've removed myself as the assignee, so it's up for grabs.

**Comment by piotrzarzycki21** [comment]
@joshtynjala thanks for spent time on that. I will then try to investigate it.

**Comment by rat-moonshine** [comment]
Thank you @joshtynjala for your investigation on this.

I pushed a fix (in TextLineRenderer), and also followed through the test cases uploaded by me and Piotr, I didn't found any problem so far. @piotrzarzycki21 please report, if you notice such null pointer exception again.

I'm closing this issue for the time being to push with 1.7.0.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine this great! I will add to the change log information about fixing that issue. If users see something which we didn't discover we may have some feedback on that.
