### ISSUE TITLE
Guide for Switching from Flash Builder to Moonshine

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#761]
As a 32-bit application, Flash Builder is no longer working on macOS Catalina and Big Sur.   We would like to have some documentation on our website to show how they can easily migrate their Flash Builder projects to Moonshine.

This should include at least these topics:
- How to open Flash Builder projects in Moonshine
- How to run the Flash Builder projects in Moonshine

Other topics to consider:
- How to convert dependencies (if this is not fully automatic)
- Debugging - this is an important IDE feature, so we should make it clear that this is still available in Moonshine
- Any other common problems that @rat-moonshine or @piotrzarzycki21 can think of

I think we already made opening Flash Builder projects easy in Moonshine, so there may not be much new to add for these topics beyond the basic documentation for the features.

**Comment by Aszusz** [comment]
I made a draft video, uploaded it to vimeo as unlisted and send the team a link via email.
I'm going to record this again once I get feedback. There may be some volume/sound quality issues that I'll fix in the final version.

**Comment by rat-moonshine** [comment]
_00:12-00:22_
You may want to improve this part; Support to run FB is broken since it's 32 bit and since macOS (not Windows) Catalina the OS runs only 64bit applications. 

_02:09-02:11_
Saving the settings by the alert of closing the tab might confuse a viewer in a short time involvement, perhaps instruct to save the settings by its Save button

_02:21-02:25_
The same can be done through the Project menu

_02:26_
In my opinion, you should demonstrate with a more generic template of Flash Builder project rather than with Prominic project; Although this won't create a security issue but better to demonstrate with general stuff.

_03:46- 4:08_
This step is unrelated to importing a Flash Builder project. If you can demonstrate with a general template/project, this step wouldn't require at all.

**Comment by Aszusz** [comment]
@rat-moonshine 
Thank you for a lot of very valuable feedback. I'll be sure to adjust my video to all of it. Changes 1-3 are clear to me.

> 02:26
In my opinion, you should demonstrate with a more generic template of Flash Builder project rather than with Prominic project; Although this won't create a security issue but better to demonstrate with general stuff.

I thought XHTMLConverterCli is the project I got from you to showcase in this video. If you want me to use a different project please give me a link to the repo. Or would you rather see me use hello world project?

> 03:46- 4:08
This step is unrelated to importing a Flash Builder project. If you can demonstrate with a general template/project, this step wouldn't require at all. 

I thought this is what @JoelProminic ment by "How to convert dependencies (if this is not fully automatic)". Wouldn't the user encounter the same problem when using external flash libraries?

**Comment by rat-moonshine** [comment]
> I thought XHTMLConverterCli is the project I got from you to showcase in this video. If you want me to use a different project please give me a link to the repo. Or would you rather see me use hello world project?

I may have missed the detail of the conversation and I thought you want a Flash Builder setup project for your testing, I'm sorry it seems I misunderstood that requirement.

In general, I would like to see a simple Hello World example during a tutorial if not a step-by-step particular application development.

> I thought this is what @JoelProminic ment by "How to convert dependencies (if this is not fully automatic)". Wouldn't the user encounter the same problem when using external flash libraries?

I think that is really a way we might want to show since Flash Builder configuration stores paths with keywords that are sometimes readable by the Flash Builder only.

We may want to suggest to check and update the settings as requires, post-import, and maybe show to how to set a 'libs' directory in that case.

**Comment by Aszusz** [comment]
Justin accepted the video. I'm making it public:
https://vimeo.com/491398283
