### ISSUE TITLE
Support for .ondiskproj Extension

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#799]
I tried opening a Domino On Disk Project in Moonshine by double-clicking on the .ondiskproj file in macOS Finder.   macOS did not recognize Moonshine as a valid application for this file.   I went through the prompt to manually select Moonshine, but it opened the file in an Editor rather than opening the project.

**Comment by JoelProminic** [comment]
@rat-moonshine added the extension [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/MoonshineDESKTOP-app.xml#L275).  We'll need to test on both macOS and Windows to make sure it opens properly as a project.

**Comment by JoelProminic** [comment]
On macOS, I confirmed that double-clicking a .ondiskproj file will open the project in Moonshine.

However, I see that LSHandlerRank (see #596) is missing in the plist on macOS

                                <key>LSHandlerRank</key>
                                <string>Owner</string>

On Windows, I found that the .ondiskproj extension was not recognized.  However, I see that .as3proj files are also not recognized - is this a known issue for Windows?

**Comment by rat-moonshine** [comment]
I have added the requisite attribute in `info.plist`, this should work now. However, I do see that known project files are not recognizable anymore on Windows Explorer as Moonshine files. I don't remember when this broken. This used to work; Perhaps, this is something since Harman SDK? We didn't had any changes to the file-association section for a long time, so I don't suspect any code-changes that fail this area; Furthermore, the way of file-association works simply by declaring in the `*-app.xml` configuration which haven't changes.

I tried to build locally on Adobe AIR 32 on Windows, but I continue to get `Error: Store IsDiskFile()` failed error during package signing, this could be something at my side of settings. For now, I didn't spent much time investigating what is causing the error during signing at my local.

**Comment by JoelProminic** [comment]
Yeah, I see that LSHandlerRank is set correctly now, and the double-click functionality worked well.

```
            <dict>
                <key>CFBundleTypeExtensions</key>
                <array>
                    <string>ondiskproj</string>
                </array>
                <key>CFBundleTypeMIMETypes</key>
                <array>
                    <string>text/plain</string>
                </array>
                <key>CFBundleTypeName</key>
                <string>Moonshine Project Configuration File 5</string>
                                <key>LSHandlerRank</key>
                                <string>Owner</string>

                <key>CFBundleTypeRole</key>
                <string>Editor</string>
            </dict>
```

I created a separate issue to track the extension errors for Windows:  #800.    I'll keep this issue open until we can test the extension on Windows.

**Comment by JoelProminic** [comment]
#800 is fixed, and I confirmed that I can open .ondiskproj files as project on macOS and Windows
