### ISSUE TITLE
Unexpected Default Position for Moonshine Window

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#819]
During testing today, I noticed that Moonshine on macOS was not opening in the center position when it was not maximized.
1. Restore Moonshine to the default size
2. Restart Moonshine.  BUG:  it opens on the bottom of the screen, and closer to the left than the right.
3. Move Moonshine to a different location on the screen
4. Restart Moonshine.  BUG:  it opens in the same position as step 2.

**Comment by rat-moonshine** [comment]
I didn't had a chance to look into this today. I shall see this on Monday first thing.

**Comment by rat-moonshine** [comment]
This is now ready to be tested on master now. Please, check.

**Comment by rat-moonshine** [comment]
I think this turning out even more tricker than I initially thought. I able to produce the problem on macOS once I changed the macOS Dock from left to right. 

I see the problem produced in following steps in my case - EVEN when I completely stopped any internal sizing/placement handling to the application window:

1. Open Moonshine - make its size more smaller than its default size
2. Restart Moonshine
3. Moonshine starts with its last known size (which was less than its default size) and at the center of the screen
4. Maximise the application
5. Restart Moonshine
6. Moonshine starts maximising in expected manner
7. Double-click on its title-bar to have the window restored - expected to be restore to the application's default size
8. Application changed its size to the default one 
9. Application window automatically placed itself to the lower-left corner of the screen

In the step.9 - I see it as a bug to macOS because I didn't put any external force to alter its size/placement at this time. 

To cement my thought if this a macOS bug - I opened Chrome:

1. After starting Chrome give it some manual sizing
2. Quit completely
3. Restart Chrome, it opens by the last known size and at the center of the screen
4. Double-click to its title-bar to maximise
5. Quit completely
6. Restart Chrome, it opens in maximise mode
7. Double-click to its title-bar to restore 
8. Chrome window automatically placed itself to the lower-left corner as was the Moonshine

I want to keep this as macOS bug and I don't have any immediate offering on this. 

Beside these, I made couple of changes in the internal handling which should make the sizing/placement process more correct, and the following behaviour are expected to be seen:

1. Moonshine restarted in maximised mode
2. Double-clicking the title-bar to restore
3. Moonshine changed to its default size
4. on macOS - the placement is not guaranteed [can't fix]

I'll going to test the updates on Windows shortly.

**Comment by rat-moonshine** [comment]
So I did an orthodox fix to overcome the problem explained above. This looks good on macOS during my tests. Windows tests are pending.

**Comment by rat-moonshine** [comment]
With couple of tests, on Windows the updates looks good also. Please check.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine after your last commit with newest nightly I have weird behavior for Moonshine on my Mac OSX Catalina.
1) Run Moonshine
2) Click minimize

It will minimize Moonshine and automatically maximazie. In results I cannot minimize Moonshine at all.

**Comment by rat-moonshine** [comment]
I pushed a fix. Please give this a test after Bamboo build completes.

**Comment by JoelProminic** [comment]
When I tested this yesterday on macOS, I found that Moonshine initially restored to the bottom left, but the height was reduced to an unreasonable size (something like 100 px).  When I restarted Moonshine, it opened in the center, but it the smaller height.

My concern for this is that users who are upgrading from 3.0.0 might see the same behavior.  I'd like to do some tests for this.

**Comment by rat-moonshine** [comment]
For my reference, here's the test procedure that @JoelProminic once had:

1. Center Moonshine (build. 1917)
2. Maximize Moonshine
3. Close Moonshine
4. Install the new build (build. 1920)
5. Open Moonshine: it starts maximized
6. Restore Moonshine: It is resized and moved to the bottom right
7. Restart Moonshine: It reopens in the center, with the updated size

**Comment by JoelProminic** [comment]
I tested this on a different machine running macOS 10.13.4 (High Sierra), which was still on Moonshine 2.6.0.  I saw this behavior:
1. Open old Moonshine
2. Confirm that it opens in the center of the screen (NOTE: I see it initially opens in the bottom left, but then adjusts to the center)
3. Maximize Moonshine
4. Close Moonshine
5. Update to the latest 3.1.0 nightly build
6. Open Moonshine
7. BUG:  Moonshine now opens in the bottom left.  The window is not resized, though
8. Drag Moonshine to the center
9. Restart Moonshine
9. BUG:  Moonshine reopens in the bottom left again.

So I didn't see the resize issue again, but I am seeing that the window repositioning doesn't work on this High Sierra machine.

**Comment by rat-moonshine** [comment]
Can you perform the same action on Chrome in High Sierra, and see if you can witness the same problem (?) If this something affects all windows chrome on High Sierra, then perhaps it'd be tricky to find out a solution but we can only try.

**Comment by JoelProminic** [comment]
This is the behavior I saw for Google Chrome on High Sierra:
1. Open Google Chrome.  The window does *not* open in the bottom left position like I reported for Moonshine
2. Move the Google Chrome window
3. Restart Google Chrome.   The window reopens in the same position

Also note that I see this same behavior on macOS Catalina, so I can't reproduce the behavior you reported for Chrome.  I'm not convinced that this is a general macOS bug.

**Comment by rat-moonshine** [comment]
From my previous tests to Chrome https://github.com/prominic/Moonshine-IDE/issues/819#issuecomment-837887333 it involves maximizing the window, which also matches to your earlier test processes on Moonshine. 

Did you also consider your tests on Chrome with maximizing steps @JoelProminic (?) I thought to mention this as I haven't seen its mention in your test process.

**Comment by JoelProminic** [comment]
No, I didn't include that in my tests today.   I tried this again, maximizing Chrome each time before I restarted it (Note that Chrome goes it to full screen, rather than just maximizing the window like Moonshine).   I this case, I noticed that Chrome reopened in the center of the screen for Catalina, and off center (but not in the bottom left like Moonshine) for High Sierra.

**Comment by piotrzarzycki21** [comment]
I think this issue should be moved to next release.

**Comment by JoelProminic** [comment]
My main remaining concern for this was that it would cause really annoying problems like what I reported [here](https://github.com/prominic/Moonshine-IDE/issues/819#issuecomment-839918290)

> When I tested this yesterday on macOS, I found that Moonshine initially restored to the bottom left, but the height was reduced to an unreasonable size (something like 100 px). When I restarted Moonshine, it opened in the center, but it the smaller height.
> 
> My concern for this is that users who are upgrading from 3.0.0 might see the same behavior. I'd like to do some tests for this.

Since no one else has reported major problems like this, I'm fine with bumping this to the next release.   If no one else is seeing remaining oddities for when not running in fullscreen, we could probably close this issue instead.

**Comment by rat-moonshine** [comment]
> No, I didn't include that in my tests today. I tried this again, maximizing Chrome each time before I restarted it (Note that Chrome goes it to full screen, rather than just maximizing the window like Moonshine). I this case, I noticed that Chrome reopened in the center of the screen for Catalina, and off center (but not in the bottom left like Moonshine) for High Sierra.

Unfortunately, I can have this constantly produce every time using any non-Apple software, on Catalina. I tested with Skype, Visual Studio Code:

1. Open the application
2. Resize it to somewhere at right side
3. Quit completely
4. Re-open - the application opened to the position and size before you restarted - this is good
5. Double-click to its title-bar to maximize
6. Quite completely
7. Re-open - application opened maximised 
8. Double-click on its title-bar to have this restored 
9. Application resized to bottom-left corner - as was Moonshine

I still feel there is some sizing/placement issues with macOS (Catalina) which applies against non-Apple software; When the Apple software either opens to a fixed size always, or do-not restored form its maximise position after being restored (this is odd).

**Comment by piotrzarzycki21** [comment]
I would like to move this issue to the next release.

**Comment by rat-moonshine** [comment]
We can bump this issue. But if there is some issue inside the macOS handling, then it is just keep spending our time on this.

**Comment by JoelProminic** [comment]
Okay, I don't want to spend more time on this issue if it is not causing trouble for anyone currently.  I'll move this to the next release.

**Comment by JoelProminic** [comment]
I'm going to close this issue in 3.1.0 so that the update is tracked.  We can create a new issue if we have more problems.
