### ISSUE TITLE
Add option "Copy Path"

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#82]

**Comment by piotrzarzycki21** [comment]
"Copy Path" option has been added to the right click context menu in Project Tree.

**Comment by atinprominic** [comment]
It would be great if the option - "Open in Explorer" is there. On mac it will be really helpful to directly open a path in Explorer.

**Comment by piotrzarzycki21** [comment]
@atinprominic thanks for the suggestion I just added separate enhancement for that work #122. I called also that option similar as it is in other IDE "Show in Explorer".

**Comment by atinprominic** [comment]
Thanks

Can you suggest me what else I can test?

Thanks
Atin



                                                                                                                   
  From:       "Piotr Zarzycki" <notifications@github.com>                                                          
                                                                                                                   
  To:         "prominic/Moonshine-IDE" <Moonshine-IDE@noreply.github.com>                                          
                                                                                                                   
  Cc:         "atinprominic" <atin@prominic.net>, "Mention" <mention@noreply.github.com>                           
                                                                                                                   
  Date:       27/12/2017 03:21 pm                                                                                  
                                                                                                                   
  Subject:    Re: [prominic/Moonshine-IDE] Add option "Copy Path" (#82)                                            
                                                                                                                   





@atinprominic thanks for the suggestion I just added separate enhancement
for that work #122. I called also that option similar as it is in other IDE
"Show in Explorer".


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by piotrzarzycki21** [comment]
"Copy path" is disabled for Visual Editor context menu. I'm reopening for fixing that bug.

**Comment by JoelProminic** [comment]
I tested this feature in Mac OS X and Windows, and it seems to work properly.

Both "Copy Path" and "Show in Explorer" work for a Visual Editor in my tests.
