### ISSUE TITLE
Lagging code completion list in Royale project

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#87]
I'm experiencing huge lag in usage of code completion list with Royale. Lag is enough big that I cannot smoothly work. I cannot figure out whether this is something broken with framework or in the plugin. 
Issue occurs when I'm in "Script" section, or when new component is being added to MXML. However showing attribute lists for component doesn't have any problems. - It's working fast. 

In general I'm waiting for completion list couple of seconds. Memory of Java process increasing. 
![image](https://user-images.githubusercontent.com/24554795/33528452-d3db6136-d860-11e7-9efb-894da9fb23a2.png)

Java Version: 8 u152 64bit
Scenario is simple - If you have some Royale project and start writing in Script section of some MXML file using code completion.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 Does the same issue occur with FlexJS?

**Comment by joshtynjala** [comment]
@piotrzarzycki21 I just committed some major optimizations to TextLineRenderer. I was able to significantly reduce the level of garbage collection happening during typing. Previously, every time that the text changed, a new Flash Text Engine TextLine was created, and the old one was removed. Now, it attempts to reuse the existing TextLine, and I found some other things that could be reused instead of recreated from scratch.

I'm not sure if this are related to your issue, but I did see measurable improvements to performance when profiling with Scout.

**Comment by piotrzarzycki21** [comment]
@joshtynjala today I have tested code completion more and it was working ok. It was after changes from Harbs where he make separate namespace for HTML module. It is currently using `library://ns.apache.org/royale/html` instead `library://ns.apache.org/royale/basic`. 

We can close safely issue if you are not going to make more changes.

Thanks!

**Comment by joshtynjala** [comment]
Thanks for the update, @piotrzarzycki21. I don't have any further changes.

**Comment by piotrzarzycki21** [comment]
@joshtynjala, @rat-moonshine we have to get back to that issue. I just started to play with 1.7.0 and initially I thought that code completion doesn't work completely. I have setup Moonshine sources in Moonshine and use Flex SDK 4.16.1. 

1) Opened two projects MoonshineDESKTOPevolved and MoonshineShareCore. Java processes looks like that.
![image](https://user-images.githubusercontent.com/24554795/33794487-6aabf830-dccd-11e7-9c3f-b8393567f5e3.png)

2) I go to the TreeView file and try to initialize code completion in Script section Ctrl + Space. I got increased memory of one of the process to 1GB and CC didn't show up. I have waited about 10 seconds and it finally shows.
![image](https://user-images.githubusercontent.com/24554795/33794504-b10c4c9e-dccd-11e7-96a4-1109674f1108.png)

3) Later was a bit better CC showed faster, but it wasn't enough acceptable and really lagging. After couple of usage CC memory increased a bit.
![image](https://user-images.githubusercontent.com/24554795/33794517-f36079b2-dccd-11e7-9309-037738709793.png)

4) I closed both projects (right click on project and choose context menu) but those two Java process wasn't go away along with closed projects. @rat-moonshine could we introduced here during some changes that problem ?

5) I have opened some Royale project and I saw three process, those two which wasn't closed in the previous step and new one for that project. Note in that case that I have as main SDK setup Apache Flex SDK and custom one for this project (right click on project "Settings") newest nightly build of Apache Royale. Code completion didn't work at all!
![image](https://user-images.githubusercontent.com/24554795/33794598-f8532b94-dcce-11e7-8a0e-b3718cc10b15.png)

6) I have closed Moonshine and processes go away. I did open it once again, setup main SDK in the settings Royale, open again the same project and try to show CC in some Script section. Memory didn't increase so significant, but CC show up after 5 seconds - lagging. 

I tried to add some component in MXML - The same lag.
I tried to add some attributes - it's working fast and show immediately.
 
![image](https://user-images.githubusercontent.com/24554795/33794622-828c9a52-dccf-11e7-84a0-952e49ec7e5a.png)

I cannot figure out where the problem is, but it would be great if someone could also play on his Windows machine with that. Yesterday Olaf report me that he tried Moonshine and CC wasn't work for him at all. - I have asked him to document here what has happened. I hope he get back to us with details.

**Comment by rat-moonshine** [comment]
By every space key press CC list is open-up and it takes more than 1 second (to show). Until that happen editor also blocks all the activity of user (to the editor). Thus if I want to write something like this:

`public static const ABCD`

It halts me 2-3 times to write the full sentence. This behavior greatly disappoints the editor usability and may encourage users to less use the editor. 

I suggest to stop CC list open upon space keypress (at least as long we can't able to populate CC like a blink). Make it available only when ":" or Ctrl+Space key pressed.

![ccproblem](https://user-images.githubusercontent.com/24370870/34027611-d7e4ae8c-e183-11e7-9f5a-abc704cab2d7.gif)

**Comment by piotrzarzycki21** [comment]
@rat-moonshine do you see duplicate entries in code completion ? My CC again is almost unusable with Royale. 
@joshtynjala I see code duplication in CC:

![image](https://user-images.githubusercontent.com/24554795/34073182-1e3d051c-e294-11e7-858f-ec7163c8917a.png)

The same is being seen in VSCode - I've asked on [dev list Harbs](http://apache-royale-development.20373.n8.nabble.com/Duplicated-TextNode-in-HTML-module-tp1250p1253.html). 

Maybe that's the reason of slowness.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 Those are likely to be Royale components with the same name, but in different namespaces. Don't let the duplicate ns1 prefix fool you. It's just default prefix for namespaces that don't have hard coded prefixes (like fx, js, mx, or s).

**Comment by piotrzarzycki21** [comment]
@joshtynjala I think it may not be the case. Look for example on Accordion and some beads:
![image](https://user-images.githubusercontent.com/24554795/34073346-f54bb0dc-e297-11e7-991b-e50816527645.png)

**Comment by joshtynjala** [comment]
@piotrzarzycki21 The js prefix can apply to both basic and express.

**Comment by piotrzarzycki21** [comment]
Accordion is not part of the Express module. I'm trying to find cause in the Royale.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I just commit code which allows to show CC only for specific set of keys. Maybe some day we will figure out some faster mechanism and bring back CC to the previous state. I have no problem with usage CC only when I need it. 

@joshtynjala so far I haven't found any useful information which allows me to understand duplication nor slowness.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 I just investigated the duplication issue in VSCode. I looked at both Accordion and ContainerBase. I tested with FlexJS 0.8, since that's what I had conveniently available, but my findings should apply to Royale too.

1) If I set the targets compiler option to SWF, there is no duplicate entries. Accordion and ContainerBase are only defined in Basic.swc.

2) If I set targets to JSFlex (which should be the same with JSRoyale), then the Accordion component is defined in both BasicJS.swc and EffectsJS.swc. ContainerBase is defined in BasicJS.swc, MaterialDesignLiteJS.swc, ChartsJS.swc, HTMLJS.swc, HTML5JS.swc, FlatJS.swc, EffectsJS.swc, ExpressJS.swc, and MobileJS.swc.

This leads me to believe that the compiler options for the JS SWCs are not correctly configured.

I looked at *frameworks/js/projects/EffectsJS/src/main/config/compile-js-config.xml*, and I can see that CoreJS.swc and BasicJS.swc are both on the **library path**. I suspect that this is the reason for the duplication. This will compile the classes from CoreJS.swc and BasicJS.swc into EffectsJS.swc. These SWCs should be on the **external-library-path** instead so that they will be available at compile time, but they won't be included in the final SWC.

**Comment by piotrzarzycki21** [comment]
Ok @joshtynjala I will than post that on Royale dev list.

**Comment by joshtynjala** [comment]
Here are my results on the lag investigation so far:

1) VSCode does not have the same lag. The list appears almost intantaneously.

2) Moonshine is not requesting completion items from the language server too often.

3) Once the completion list is displayed, typing more characters or pressing backspace filters the list without lag.

4) There's a huge spike in garbage collection at the same time that there's a lag.

I haven't figured out the exact cause yet, but these are some good clues. I will continue investigation throughout the coming week.

**Comment by piotrzarzycki21** [comment]
@joshtynjala Thank you for the details. Just last question, are you seeing this "spike" on language server ?

**Comment by joshtynjala** [comment]
@piotrzarzycki21 The GC spike is in Moonshine. I can see it in Scout.

**Comment by joshtynjala** [comment]
Further investigation today shows that the time between when completion is requested from keyboard input and when Moonshine receives raw data from the socket is between 1-2 seconds. Since VSCode does not seem to have the same problem, the bottleneck can't be in the language server itself. It must be somewhere in the custom communication layer that Moonshine uses to integrate with the language server.

Moonshine communicates with the Java process using AIR's XMLSocket API, and VSCode communicates with the Java process over stdout/stdin. Scout shows that there's a lot of activity related to XMLSocket for several frames before the completion list is shown. Perhaps XMLSocket is particularly slow. I will try to modify Moonshine to use stdout/stdin too, and hopefully that will speed things up.

**Comment by piotrzarzycki21** [comment]
@joshtynjala thanks for the information. Yesterday I looked also into the Scout and saw that spike there. Some analysis leads me also to the XMLSocket, but I couldn't believe that it can be so slow. To me it was even more than 2 seconds.

**Comment by joshtynjala** [comment]
I decided to try using Socket instead of XMLSocket. I figured that Socket might have less performance overhead, since it works with raw bytes. It would also be an easier conversion compared to switching to stdin/stdout with NativeProcess. Unfortunately, I determined that Socket also requires many frames to read all of the data included in the language server's completion response.

I determined that AIR seems to make 65536 bytes available from the Socket per frame. 64 KB. This seems like it might be AIR throttling network data to keep the frame rate from falling too low. As far as I know, there's no way to change this behavior.

It's possible that the stdin/stdout from NativeProcess is not throttled this way, so I will continue my investigation in that direction.

**Comment by rat-moonshine** [comment]
@joshtynjala (In general) can we prevent CC list generation on Space key press? At this moment writing a text with lots of spaces taking bit longer time (due to the CC list generation delay), i.e. `public static const MY_VAR`. Perhaps, we can avail the generation on ` . `,` : `, and Ctrl+Shift+Space key presses.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I did by those changes https://github.com/prominic/Moonshine-IDE/commit/813621714894bf8a0b07b9d09122b739a7517ba2 but Josh rolled it back. They in general do not allow for showing code completion when you are typing, but rather showing by selected special keys. Not sure how to do this differently. I'm for Ctrl + Space, definitely not Ctrl+Shift+Space.

**Comment by piotrzarzycki21** [comment]
If Josh fix this lag which we are talking about here, to me showing CC doesn't have to be so restrictive as in my commit, cause it will be working fast. In that case only thing which we could prevent is showing CC on "Space" eventually "Tab", the rest could be as it is now.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 I missed that you had removed space as a trigger key. Sorry about that! I removed it again.

**Comment by joshtynjala** [comment]
> At this moment writing a text with lots of spaces taking bit longer time (due to the CC list generation delay)

@rat-moonshine Hmmm... If the creation of the completion list is adding lag to characters appearing on screen while you type, someone definitely needs to address that too. I was not aware that this was also an issue.

**Comment by piotrzarzycki21** [comment]
I think your roll back on my commit helps with that problem. The second one is that which you have diagnosed with XMLSocket. If that one you will be able to fix we will be good.

**Comment by joshtynjala** [comment]
Commit BowlerHatLLC/vscode-nextgenas@d659ec971f3d85be18ee4e76a80e7663babfd752 removes duplicate class/interface entries from the completion list. I did a quick test with a Royale project in Moonshine, and it seems to reduce the time Moonshine takes to handle completion requests in half. Because Royale components were duplicated in so many SWCs, there were thousands of extra entries in the completion list!

**Comment by piotrzarzycki21** [comment]
I just tried it and it's definitely faster than it was. I still feel this small lag at the beginning, but it's a way better. I will try to work with it a bit more and will see how would be my feeling after some time.

**Comment by joshtynjala** [comment]
A longer lag the first time completion is requested is not completely unexpected. The compiler its loading the project for the first time. After that, it's like an incremental compile, so it goes faster.

**Comment by piotrzarzycki21** [comment]
@joshtynjala are you planning to look into the change type of communication with language server ? I'm using codecompletion.jar with your changes above all the time. I still feel this lag at the beginning - it is definitely not annoying as it was before, but could be better. 
I'm asking cause I'm thinking about closing this one and see in the future whether users will complain about CC.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 Yeah, I'm planning to look into it over the next couple of days, if the release of vscode-nextgenas goes well. Otherwise, I'll look at it early next week.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 According to Scout, recent changes to the CompletionManager and CompletionItem classes are creating a huge number of temporary objects, including Strings and Arrays. In particular, the sorting that you implemented in commit 7fdf168895868145d1ce86238132623677e67de6 seems to create about 80000-100000 (depending on which SDK is being used) temporary strings that need to be garbage collected. The total garbage collection after showing the completion list takes longer than 1 second on my computer.

**Comment by piotrzarzycki21** [comment]
@joshtynjala I will look into the Scout and try to make something with that. Not sure what to do yet with the sorting.

**Comment by piotrzarzycki21** [comment]
It looks like the CompletionManager itself creating too much CompletionItem if I understand you correctly. That's the main place for optimize things ?

**Comment by joshtynjala** [comment]
Every time that ObjectUtil.stringCompare() is called in sortCodeCompletionMenu, it seems to call toLowerCase(), which creates a new String object.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 I have found a way to avoid the garbage collection that was introduced after the list sorting was added. CompletionItem now stores copy of the string returned by toLowerCase() in a variable so that it can be used during sorting. On my computer, the time required for garbage collection when the list is being displayed dropped to about 0.4-0.5 seconds.

**Comment by joshtynjala** [comment]
As noted in [Piotr's comment here](https://github.com/prominic/Moonshine-IDE/issues/259#issuecomment-391971546), the lag has been reduced significantly in the process of implementing the language server protocol correctly.
