### ISSUE TITLE
[UI Builder] Save Confirmation

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#97]
This is related to some of the problems discussed in #69, but I created a separate issue so that this would be more on-topic.

I am seeing behavior like this with the visual editor: 
1. Create a new Visual Editor project.
2. Add a label to the interface
3. Without saving, click Project > Export...
4. He exported project does not include the label.

If I save before step 3, it works properly, but there is no visual indicator or warning that I need to save.  I propose that we add these updates to help avoid this problem:
- Show an asterisk in the tab name if the visual editor mockup is unsaved, similar to how normal text files work.
- If the user tries to export the project without saving, show a prompt asking the user whether they want to save before exiting

If you try to Build & Run a normal project without saving, Moonshine shows a prompt like this:
![2017_12_06__save_prompt](https://user-images.githubusercontent.com/24532731/33676278-f9348ad6-da7a-11e7-8736-86e196f8cabc.jpg)

I think we should be able to reuse this prompt, but the title would need to be updated to "Save & Export".  (Also, the text should be "at least" instead of "a least").

**Comment by JoelProminic** [comment]
The Moonshine 1.7.0 release has been submitted for review, but we can resubmit it if we want to include this fix.

**Comment by piotrzarzycki21** [comment]
@JoelProminic let me look into that tomorrow morning my time. We will loose some time, but I would like to have really good quality in case of that release.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have fixed issue as you suggested. Unfortunately I have found one scenario in Visual Editor where Moonshine is not notified about changes for properties width/height. This is something where I have to spend more time and fix will be inside Visual Editor. I will raise separate issue. We can proceed with the release.

**Comment by rat-moonshine** [comment]
In my opinion, this style is bit off current Moonshine popup alert style:
![image](https://user-images.githubusercontent.com/24370870/33708161-b16649e8-db5f-11e7-8545-88e094958ef4.png)

In the above popup, it is also not clear if user choose to not to show again (checkbox) - by default Moonshine will save or not-save a file next time?

If this above style is showing during "Build & Run" (when there are unsaved editors open), then that suppose to replace by this popup:
![image](https://user-images.githubusercontent.com/24370870/33708235-e48ead74-db5f-11e7-9a03-fbdf56775b82.png)

For individual file (like in the case of VE editor) save notification, Moonshine has its existing style - 
![image](https://user-images.githubusercontent.com/24370870/33708279-0332e9ac-db60-11e7-903a-ca4479954ef5.png)

Or, can be opt for the 2nd shown popup style.

In case of exporting the VE project to a Flex project, the proposed name should come something with a suffix, i.e. "[actualVEprojectName]_exported". So we can minimize this probability:
![image](https://user-images.githubusercontent.com/24370870/33708429-6e02c784-db60-11e7-952e-4cd8a71027a7.png)

Except above, the problem mentioned in this issue seems fix now. 

I also have a suggestion:
![image](https://user-images.githubusercontent.com/24370870/33708682-1ab8b2d6-db61-11e7-92d2-32fd0d65606a.png)

In above image it's not very clear which tab is active at a time, because both tabs demonstrates darker color. The inactive one recommend to tone down to something that feels not active.

**Comment by piotrzarzycki21** [comment]
After some conversation with Santanu we have decided that it would be better if I show popup "Save Resources" which will better reflect in case of saving many files.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine I did apply following changes:
- I have used "Save Resources" popup instead "Save and Export"
- I have applied your suggestion with suffix "_exported" for exporting project
