### ISSUE TITLE
Visual Editor exported Flex project not showing all files when exported

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#99]
I have multiple VE files in a Visual Editor project. 

When I exported the project, its Flex project opens immediately after being exported. I noticed that only the main MXML file shown up in the opened Flex project:

![image](https://user-images.githubusercontent.com/24370870/33712031-fe351842-db6b-11e7-814e-3b22ab487ecc.png)

After a close and re-opening the Flex project - this time it shown all the MXML files inside:

![image](https://user-images.githubusercontent.com/24370870/33712059-1a14e772-db6c-11e7-9f0d-c40b9c89fd23.png)

**Comment by piotrzarzycki21** [comment]
I have found cause of that issue and fix is not so trivial. I would like to describe it here. Once we export the project we need to refresh Project Tree and actually I'm doing that. Unfortunately the function which is responsible for refreshing simply do not pickup newly exported project for refresh.

It is important to assume that we are exporting our project to the same directory which is Visual Editor project.
Once we export project and got event for refresh in our array we will have following entries:

d:\Moonshine Tests\NewVisualEditorProject
d:\Moonshine Tests\NewVisualEditorProject_exported

Line [148](https://github.com/prominic/Moonshine-IDE/blob/8fe1fd821174fa94033b48be88da3bff56b35007/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L148) `if (dir.fileBridge.nativePath.indexOf(fw.nativePath) > -1)` discover for the first entries that this project should be refreshed and finish the job due to `return`.

Fix can be that I will delete return and allow to refresh both, but is this acceptable actually ?

**Comment by piotrzarzycki21** [comment]
Pull my current changes. The case is if your Visual Editor project and exported project are in the same directory, by the same I mean as you pointed in your case: c:/user/Desktop/. Than during refresh only first location is taken for the refresh. The [projectFolders](https://github.com/prominic/Moonshine-IDE/blob/cd07b85ad4f5867dbeeda65da635487e44bafea6/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L143) array will contains following locations:

`[c:/user/Desktop/NewVisualEditorProject, c:/user/Desktop/NewVisualEditorProject_exported]`.

I'm sending event to refresh this location `c:/user/Desktop/NewVisualEditorProject_exported`. Function is taking from the array first path. We have following comparision:

`"c:/user/Desktop/NewVisualEditorProject_exported".indesOf("c:/user/Desktop/NewVisualEditorProject") > -1` - Since it is true we are refreshing first path instead of second one and ends refresh process.

Go through the scenario and set break point on that line.

**Comment by rat-moonshine** [comment]
Understood. What if you change this line slightly this way (at line#148):

`if ((dir.fileBridge.nativePath + dir.fileBridge.separator).indexOf(fw.nativePath + dir.fileBridge.separator) != -1)`

**Comment by piotrzarzycki21** [comment]
@rat-moonshine thanks it's working now!

**Comment by JoelProminic** [comment]
I confirmed that the other visual editor files showed up in the new project without out a refresh.  I tested an extra file in src, and a file in a nested directory.
